### ISSUE TITLE
Javascript in custom modules

### ISSUE THREAD

**Issue by antonkor** [elegantthemes/create-divi-extension#101]
Havn't found any documentation on this anywhere so I thought i would ask.

1. While creating a module that requires JS to render (in my case a Mapbox map), where do we put the JS? right now i have it returned in the render method but that feels really wrong:
https://cl.ly/3u0H36442g1n

2. would i enqueue the necessary scripts (mapbox-gl.js & mapbox-gl.css) in my functions.php file or is there a way todo it from the module. seems kinda weird having to enqueue those scripts in functions.php since how do you build the logic if that module is even used on a page anyway.

3. Since I have the react bit working perfectly on the FrontendBuilder, is there a way to utilize that code on my published page:
https://pastebin.com/47GaBGFE

I guess the real question here is; Can you just use the react component to work on the published page or do I need to re-write the code on the php side of the module and utilize it's own scripts.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
I was asking me these question as well and this is how I deal with them at the moment. I am not sure if it is the right way.

I enqueue the script normally in my plugins main file using the wp_enqueue_script() function. You also could use wp_register_script() in your plugin and call wp_enqueue_script() in the render function of your modules php. Then I create a JavaScript file and enqueue it the same way but add the other scripts as a dependency to my own JS. Inlining the script as you do it works fine but has the downside that you end up with a lot more code then necessary. I prefer separating my PHP/HTML and JS so I can leverage my IDEs code completion etc.

Since the React component runs on the frontend, I started to enqueue my scripts directly rather than just registering them and only enqueue them in the render function but you probably could also simply import the necessary script in React but I'm not experienced enough to know how to do this.

At the moment there is no intention to re-use the render function of the React component on the frontend. It might come at one point or now. Therefore at the moment you have to re-implement the render() function in php.

**Comment by antonkor** [comment]
Yeah that's basically what I'm doing now. Hope they can streamline this a bit in the future. it feels wacky the way we're enqueuing JS outside the module codebase.

**Comment by antonkor** [comment]
Anyone have a cleaner way of doing this?

i know there are [hooks](https://www.elegantthemes.com/documentation/developers/hooks/divi-template-hooks/) (such as et_head_meta) we can use but not entirely sure where we use them, the functions.php file (again outside the divi extension).

**Comment by lots0logs** [comment]
There are multiple ways to handle it. I recommend putting it in the `scripts/frontend.js`. That file will be processed by webpack and bundled. You can even use es6 imports there. The bundled file is automatically enqueued on the frontend and in the builder.

**Comment by antonkor** [comment]
But I am relying on the data in get_fields() to generate my mapbox as shown in my first screenshot:
https://cl.ly/3u0H36442g1n

if i used scripts/frontend.js how can i reference my module?

**Comment by xxtesaxx** [comment]
Thats exactly like I do it myself. I simply add data-attributes to the outermost div in my module and give it a certain class. Then I use ".my-module-slug .my-outermost-div" as the selector in JavaScript to target my modules and just like you loop with a foreach to setup the elements. 

I highly recommend you adding the modules slug infront of your .map selector because you otherwise might cause problems if anotehr wordpress plugin or theme has elements with a map class. :)

**Comment by markospacetech** [comment]
I've been trying to get my JSX that's displaying in the Divi builder to show on the main frontend as well for the last few days and I feel like this issue might be related. 

I'm more experienced with React than Wordpress so not sure where/how to enqueuing the React scripts or some javascript file where I could render my component with ReactDOM (or wp.element.render I believe). Not sure if this will send a notification or if any will see it but I figured I'd give it a shot. Would gladly pay to get 20 or so minutes of a Divi expert's time at this point lol I feel like it should be straightforward.

**Comment by ajien** [comment]
Elementor has get_script_depends() method for this purpose. I hope Divi will also implement something similar.
