### ISSUE TITLE
Improvement Suggestion: Visibility based on array

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#12]
Back in 3.0, you could use depends_show_if only with single values while depends_show_if_not accepted an array. I just gave it a test and apparently show_if now supports arrays as well. So this is what you learn from the docs (https://www.elegantthemes.com/documentation/developers/divi-module/settings-field-visibility/)

    $fields['test'] = [
        'label' => 'test',
	'type' => 'text',
	'toggle_slug' => 'main_content',
	'show_if' => [
	    'other' => 'some-value'
	],
    ];

but this also seems to work just fine:

    $fields['test'] = [
        'label' => 'test',
	'type' => 'text',
	'toggle_slug' => 'main_content',
	'show_if' => [
	    'other' => [ 'some-value', 'some-other-value' ],
	],
    ];

The last question I now have is how the conditions are put together. Are they all concatenated with an AND? e. g. how does this turn out:

    'show_if' => [
        'a' => ['1', '2'],
        'b' => ['x', 'y'],
    ],
    'show_if_not' => [
        'c' => ['$', '€'],
        'd' => ['_', '-'],
    ]

If I understand it correctly, the setting would not show if 

* a is something other than 1 or 2
* b is something other than x or y
* c is $ or €
* d is _ or -

So all conditions must be met in order for the setting to show up, right? Maybe we can put some more complex examples in the documentation to make it easier for beginners to understand.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
Hi, we deprecated `depends_show_if/not` because they were designed with the way the classic Divi Builder works in mind. Also, since using them additionally required adding dependent fields directly to the definitions of fields they depend on using the `affects` parameter, they were pretty verbose. For those reasons we decided to do away with them and come up with something better which is where `show_if/not` came in.

We actually haven't had time to port any of our modules to the new `show_if/not` parameters (except for the Email Opt-in module) so when I wrote the documentation, I forgot that you could pass an array of values (which is sad because I'm the one who wrote the code for the entire `show_if/not` system :sweat_smile: )

Everything you've summarized is correct. The value checks are combined with `AND` in order to keep the implementation as simple as possible while still being robust enough for the majority (if not all) use cases. I'll make sure the documentation gets updated with a more complex example. Thanks for bringing this to my attention! :smiley:

**Comment by lots0logs** [comment]
Hi, we deprecated `depends_show_if/not` because they were designed with the way the classic Divi Builder works in mind. Also, since using them additionally required adding dependent fields directly to the definitions of fields they depend on using the `affects` parameter, they were pretty verbose. For those reasons we decided to do away with them and come up with something better which is where `show_if/not` came in.

We actually haven't had time to port any of our modules to the new `show_if/not` parameters (except for the Email Opt-in module) so when I wrote the documentation, I forgot that you could pass an array of values (which is sad because I'm the one who wrote the code for the entire `show_if/not` system :sweat_smile: )

Everything you've summarized is correct. The value checks are combined with `AND` in order to keep the implementation as simple as possible while still being robust enough for the majority (if not all) use cases. I'll make sure the documentation gets updated with a more complex example. Thanks for bringing this to my attention! :smiley:

**Comment by lots0logs** [comment]
[Documentation](https://www.elegantthemes.com/documentation/developers/divi-module/settings-field-visibility/) has been updated
