### ISSUE TITLE
VB :: Cannot Load Custom module in Divi Builder

### ISSUE THREAD

**Issue by manojmilani123** [elegantthemes/create-divi-extension#137]
I have created a custom divi module using all the documentation provided on the Elegant Themes website and I am unable to load my custom module in the Divi Extension created using command line. Also, is there a way to load custom html that is rendered from the module output into the module jsx file?

### Steps To Reproduce
1. I have created a extension using npx create-divi-extension "Extension Name" command
2. I have created a new custom Divi module looking at the Hello World Module
3. Inside my extension I run yarn start command to start the development server. 
4. It shows no issues over there but I cannot see the module in Divi builder both on Backend as well as Front-end

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by atanas-angelov-dev** [comment]
Hi @manojmilani123 ,

Could you please share your custom module code so that I can check for any potential issues?

**Comment by manojmilani123** [comment]
I have added below code in index.js file of the extension that I have created:

import PricingTablesExtended from './PricingTableExtended/PricingTablesExtended';
export default [PricingTablesExtended];

And within the module jsx file, I have added below code:

import React, { Component } from 'react';
// Internal Dependencies
import './style.css';
class PricingTablesExtended extends Component {
  static slug = 'insnap_et_pb_pricing_tables_extended';
  render() {
    const Content = this.props.content;

    return (
      <h1>
        <Content/>
      </h1>
    );
  }
}
export default PricingTablesExtended;

**Comment by atanas-angelov-dev** [comment]
Can you please also share the contents of your main plugin `.php` file (e.g. `my-extension.php`) and `includes/YourExtensionName.php`?

Also, could you please check if a module with the name of "Hello World" is available in the front-end builder?

**Comment by manojmilani123** [comment]
Yes, it shows hello world module but we click hello world module, it shows error on frond-end.

**Comment by atanas-angelov-dev** [comment]
You have not renamed your module so it appears as "Hello World" in the module list. Please rename all references to "Hello World", "hello_world" etc.
If you still get an error after you rename everything then please check through the User Guide:
https://github.com/elegantthemes/create-divi-extension
https://github.com/elegantthemes/create-divi-extension/blob/master/packages/divi-scripts/template/README.md

**Comment by manojmilani123** [comment]
I haven't renamed hello world, but instead I have created new module with the hello world reference.

**Comment by manojmilani123** [comment]
I am building extended version of the pricing table. So, I have created 2 classes - one for pricing table main module and then another class for pricing table items. But I am only exporting main module class from jsx file and then importing that class in includes/index.js. Let me know if those are the correct steps to setup extended version of the pricing table module.

**Comment by manojmilani123** [comment]
I was able to figure out displaying our custom module but that module throws below error:


    in Unknown (at PricingTablesExtended.jsx:17)
    in PricingTablesExtended (created by t)
    in div (created by t)
    in div (created by ETBuilderModule)
    in t (created by ETBuilderModule)
    in ETBuilderModule (created by t)
    in t (created by t)
    in t (created by ETBuilderColumn)
    in div (created by ETBuilderColumn)
    in t (created by ETBuilderColumn)
    in ETBuilderColumn (created by ETBuilderRow)
    in div (created by ETBuilderRow)
    in t (created by ETBuilderRow)
    in ETBuilderRow (created by ETBuilderSection)
    in div (created by ETBuilderSection)
    in t (created by ETBuilderSection)
    in ETBuilderSection (created by ETBuilderRoot)
    in div (created by t)
    in t (created by ETBuilderRoot)
    in div (created by ETBuilderRoot)
    in ETBuilderRoot
    in t

**Comment by manojmilani123** [comment]
I wanted to display the custom output rendered by my module.

**Comment by manojmilani123** [comment]
@atanas-angelov-dev I am waiting for 3 days now and still did not get any feedback on this issue. Can you please tell me what to do?

**Comment by atanas-angelov-dev** [comment]
@manojmilani123 I can't really help without an exact error message and the code that triggers the error as well.

**Comment by manojmilani123** [comment]
@atanas-angelov-dev  I am now able to display the custom module in the front-end but now I have to display the html output rendered by the custom module in live preview of the visual builder.

**Comment by manojmilani123** [comment]
@atanas-angelov-dev 
![screen](https://user-images.githubusercontent.com/3876061/44262036-2441e780-a237-11e8-9799-1bef57a80f15.png)

I am using the below code in my .jsx file

class PricingTablesExtended extends Component {

  static slug = 'insnap_pricing_tables_extended';

  render() {
    
	const Content = this.props.content;
	
    return (
		
     
	 
        <div class="">
				
				<div class="et_pb_pricing_table_wrap">
					<Content/>
				</div>
			</div>
      
    );
  }
}

And it shows me [Object Object] in the live preview like shown in the attachment.

**Comment by atanas-angelov-dev** [comment]
Use the following instead:
```jsx
<div class="et_pb_pricing_table_wrap">
	{this.props.content}
</div>
```

**Comment by manojmilani123** [comment]
@atanas-angelov-dev 

Still it shows the same [Object Object]

**Comment by lots0logs** [comment]
@manojmilani123 Sorry, you actually had it right the first time. Could you post the code from the render method of the child module in question?

**Comment by manojmilani123** [comment]
Below is the code from render function of child module from php file:

$output = sprintf(
			'<div class="%1$s">
				%10$s
				%9$s
				<div class="et_pb_pricing_heading">
					%2$s
					%3$s
				</div> 
				<div class="et_pb_pricing_content_top">
					<span class="et_pb_et_price">%6$s%7$s%8$s</span>
				</div> 
				<div class="et_pb_pricing_content">
					<ul class="et_pb_pricing">
						%4$s
					</ul>
				</div> 
				%5$s
			</div>',
			$item_instance_class,
			( '' !== $title ? sprintf( '<%2$s class="et_pb_pricing_title">%1$s</%2$s>', esc_html( $title ), et_pb_process_header_level( $header_level, 'h2' ) ) : '' ),
			( '' !== $subtitle ? sprintf( '<span class="et_pb_best_value">%1$s</span>', esc_html( $subtitle ) ) : '' ),
			do_shortcode( et_pb_fix_shortcodes( et_pb_extract_items( $content ) ) ),
			$button,
			( '' !== $currency ? sprintf( '<span class="et_pb_dollar_sign">%1$s</span>', esc_html( $currency ) ) : '' ),
			( '' !== $sum ? sprintf( '<span class="et_pb_sum">%1$s</span>', esc_html( $sum ) ) : '' ),
			( '' !== $per ? sprintf( '<span class="et_pb_frequency">/%1$s</span>', esc_html( $per ) ) : '' ),
			$video_background,
			$parallax_image_background
		);

**Comment by lots0logs** [comment]
Are you using partial support for the child module but full support for the parent? I'm not sure that's possible currently. I'll have to take a look when I get back to the office on Monday.

**Comment by manojmilani123** [comment]
Below is my parent modules jsx file code:

// External Dependencies
import React, { Component } from 'react';

// Internal Dependencies
import './style.css';


class PricingTablesExtended extends Component {

  static slug = 'insnap_pricing_tables_extended';

  render() {
    
    return (
		
     
	 
        <div class="et_pb_pricing_table_wrap">
			{this.props.content}
		</div>
      
    );
  }
}

export default PricingTablesExtended;

**Comment by lots0logs** [comment]
What about the child module?

**Comment by manojmilani123** [comment]
I havent created jsx file for the child module

**Comment by lots0logs** [comment]
I see. I think you'll need to create one. But let me confirm it when I'm in the office on Monday and get back to you.
