### ISSUE TITLE
Custom image module makes builder hang forever on initial load, then works after reload unless you dump your cache

### ISSUE THREAD

**Issue by fashiontimeline** [elegantthemes/create-divi-extension#138]
### Problem Description
I have a custom divi module that I use in the Divi builder. It works fine all the time EXCEPT for the first time you create a page or when using a new computer. I.e. when the builder isn't already cached. In that case, the builder hangs forever with the spinning wheel and you have to either hit the back button or reload the page. From then on the module will work fine, unless you switch to a new computer or force the browser to dump its cache. This wouldn't be a huge problem except that I use the Divi builder with scores of students each semester and this initial failure (and repeated failure as they tend to use a different computer each time) makes them hate Divi and think the whole site is janky. ANY help in resolving this would be much appreciated.  Elegant Themes said it wasn't their problem and I should ask you all... This is my first time ever using GitHub, so I apologize for any and all gaffes.

### Steps To Reproduce
1. Add new post.
2. Load Divi Builder.
3. Add columns.
4. Add FIT image/caption module (a version of the Divi image module).

### Screenshot and/or gif
I put the code in my repository.  The hang screen isn't that interesting, but here it is:
<img width="1154" alt="screen shot 2018-07-24 at 7 59 53 pm" src="https://user-images.githubusercontent.com/41654731/43172333-e2a8c52c-8f7c-11e8-84ca-a1cf3076588a.png">

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by atanas-angelov-dev** [comment]
Hi @fashiontimeline ,

I was unable to reproduce the issue - could you please open up the developer console and screenshot any errors that may be shown when you trigger the issue?

**Comment by fashiontimeline** [comment]
It was a plugin conflict.  Found it using Health Check.  Thanks for the help!
