### ISSUE TITLE
Question: How I can replicate the responsive css functions on the react component.

### ISSUE THREAD

**Issue by charles890123** [elegantthemes/create-divi-extension#143]
### Problem Description
I am using et_pb_get_responsive_status and et_pb_generate_responsive_css functions on the php module class to set the width of an image for each screen size and is working well.

Now on the react component I have this code but is always getting the wrong size of the container and is apply the last width I set on the previous screen size (phone, tablet or desktop). Is there a better way to do this. Thanks you.

static css(props) {
        const additionalCss = [{}];
        if (props.dpdac_author_image_size) {
            if (props.dpdac_author_image_size_last_edited !== undefined) {
                const responsive_active = props.dpdac_author_image_size_last_edited.split('|')[0];
                if (responsive_active === 'on') {
                    const preview_container_width = jQuery(".et_fb_preview_container").width();
                    if (preview_container_width < 767 && props.dpdac_author_image_size_phone !== '') {
                        additionalCss.push([{
                                selector: '%%order_class%% .dpdac_author_avatar',
                                declaration: `width: ${props.dpdac_author_image_size_phone};`
                            }]);
                    } else if (preview_container_width < 980 && props.dpdac_author_image_size_tablet !== '') {
                        additionalCss.push([{
                                selector: '%%order_class%% .dpdac_author_avatar',
                                declaration: `width: ${props.dpdac_author_image_size_tablet};`
                            }]);
                    } else {
                        additionalCss.push([{
                                selector: '%%order_class%% .dpdac_author_avatar',
                                declaration: `width: ${props.dpdac_author_image_size};`
                            }]);
                    }
                }
            } else {
                additionalCss.push([{
                        selector: '%%order_class%% .dpdac_author_avatar',
                        declaration: `width: ${props.dpdac_author_image_size};`
                    }]);
            }
        }
        return additionalCss;
    }

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by VladET** [comment]
@charles890123 In the `push()` method you can specify a new key called `device` and the value can be: `desktop`, `tablet` or `phone`.

Example:

```
additionalCss.push([{
  selector: '%%order_class%% .et_pb_gallery_item .et_pb_gallery_image',
  declaration: `height: ${image_height_phone};`,
  device: 'phone'
}]);
```

Let me know if this helps.

**Comment by charles890123** [comment]
@VladET Thanks you. Is working perfectly.

**Comment by charles890123** [comment]
Hi @VladET, I was wondering if it is possible to set different default values for each screen size on a range field?

**Comment by xxtesaxx** [comment]
Yes, you can use the 'responsive' => true, option on range fields. In your component, you then must check if the responsive setting is active liek `const responsive_active = props[property + "_last_edited"] && props[property + "_last_edited"].startsWith("on");`
If its on, you can set the values. The tablet setting is the property name suffixed by "_tablet" and the phone field is the property suffixed by "_phone".

**Comment by charles890123** [comment]
Hi @xxtesaxx, in what function of the react component can I use your method. Basically what I am trying to do is force the module to start with this specify range field already set with responsive activate and with default and different values on desktop, tablet and phone. Thanks for your reply.

https://www.dropbox.com/s/fqkor79esy0lnmf/Range%20Field.mp4?dl=0

**Comment by xxtesaxx** [comment]
Ah I see what you mean. In this case I would approach it differently. I have a filterable grid module and there I have set no default setting for the range field. In this case, the value in react will be "undefined" or "null" i think. Then simply check for if the value is set or not and if not, apply your defaults for desktop/tablet/phone. If there is a value though, use that value and if responsive option is activated, use the corresponding value. I guess you could try to add the _tablet, _phone and _last_edited settings fields yourself and set default on them but I'm not sure if that will work as expected.

The settings should all have the type "skip" and must be placed in the same tab/toggle like so:

    'icon_font_size_last_edited' => array(
        'type' => 'skip',
        'tab_slug' => 'advanced',
        'toggle_slug' => 'icon_settings',
        'default' => 'on|desktop', //not sure about this one 
    ),
    'icon_font_size' => array(
        'label' => esc_html__('Icon Font Size', 'et_builder'),
        'type' => 'range',
        'option_category' => 'font_option',
        'tab_slug' => 'advanced',
        'toggle_slug' => 'icon_settings',
        'default' => '96px',
        'range_settings' => array(
            'min' => '1',
            'max' => '120',
            'step' => '1',
        ),
        'mobile_options' => true,
        'depends_default' => true,
    ),
    'icon_font_size_tablet' => array(
        'type' => 'skip',
        'tab_slug' => 'advanced',
        'toggle_slug' => 'icon_settings',
        'default' => '50px',
    ),
    'icon_font_size_phone' => array(
        'type' => 'skip',
        'tab_slug' => 'advanced',
        'toggle_slug' => 'icon_settings',
        'default' => '10px',
    ),

**Comment by charles890123** [comment]
Thank you @xxtesaxx but unfortunately, your approach is not working for me or at least not in the latest Divi version. 

I tried first without set the _last_edited and just set default values for the _tablet and _phone skip fields and I put those fields on the same tab_slug and _toggle_slug without success. I try later also set _last_edited but also without success. I found on the Divi source code an argument for the range field type called 'default_tablet' and if I use it on my range field type I can set the default value for the _tablet but I don't found anything yet for the phone. 

I will continue trying, maybe I am doing something wrong.

![imagen](https://user-images.githubusercontent.com/16024719/43677765-96da8548-97d5-11e8-913f-7d2718a21734.png)

**Comment by charles890123** [comment]
Update. Is working for me now. I just added the following code to the init function on the module class.

`
        $this->fields_defaults = array(
            'dpdrp_items_width_last_edited' => array('on|desktop', 'add_default_setting'),
            'dpdrp_items_width_phone' => array('100%', 'add_default_setting'),
            'dpdrp_items_width_tablet' => array('48%', 'add_default_setting'),
        );
`
And is shoiwng the field with responsive on by default and also the defaults values for table and phone are being set.

**Comment by xxtesaxx** [comment]
Ah yeah this is a great idea, havn't thought about this one
