### ISSUE TITLE
VB :: exception when using a third-party module and clicking over a built-in text module

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#146]
### Problem Description

Hi! I would like to let you know an issue I'm having with the text modules. This is only happens when we also have a third-party module, for example I have included the module that comes with `create-divi-extension` in the video below.

This is the exception that is thrown:

```

Uncaught TypeError: Cannot read property 'getNode' of null
    at Object._onMouseUp (bundle.js?ver=3.7:16)
    at p.<anonymous> (bundle.js?ver=3.7:223)
    at b.e [as fire] (tinymce.min.js?ver=4.9.8:10)
    at p.fire (tinymce.min.js?ver=4.9.8:10)
    at o.h (tinymce.min.js?ver=4.9.8:11)
    at a (tinymce.min.js?ver=4.9.8:2)
    at HTMLDivElement.p (tinymce.min.js?ver=4.9.8:2)

Uncaught TypeError: Cannot read property 'getNode' of null
    at t.value (bundle.js?ver=3.7:223)
    at t.value (bundle.js?ver=3.7:223)
    at t.value (bundle.js?ver=3.7:223)
    at updateClassInstance (react-dom.production.min.js?ver=16.2:127)
    at beginWork (react-dom.production.min.js?ver=16.2:134)
    at d (react-dom.production.min.js?ver=16.2:158)
    at f (react-dom.production.min.js?ver=16.2:159)
    at g (react-dom.production.min.js?ver=16.2:159)
    at t (react-dom.production.min.js?ver=16.2:167)
    at x (react-dom.production.min.js?ver=16.2:166)
```

In my project I'm using a module that does not have a content field (tinyMCE) but it throws the same error when clicking over a Divi Text module. I have to close the module modal discarting the changes too, otherwise is fine (it seems fine, maybe not).

In the video you can see the error just clicking in the module itself. It's the same exception so it would help me, I'm not using a tinyMCE editor though.

### Steps To Reproduce
1. We add a third-party plugin to a page.
2. We have a text module too.
3. We enable the visual builder.
4. After clicking over the build-in text module sometimes a exception is raised (cannot read property getNode of null).

(In the example provided I have clicked directly over the third-party module instead so you can see the exception since I don't know the exact steps to get the exception when clicking over a build-in text).   

### Screenshot and/or gif

[2018-06-08 to ET support.zip](https://github.com/elegantthemes/create-divi-extension/files/2262521/2018-06-08.to.ET.support.zip)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [x] Helpful title used
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by ramonbuzon** [comment]
Same here @jcdotnet

I'm getting the same exception when using a text module and clicking over it, only happens when using a third-party module created with `create-divi-extension`.

Hope @lots0logs and the ET staff can support here
