### ISSUE TITLE
function get_fields: text type fields do not display in back end

### ISSUE THREAD

**Issue by insight47** [elegantthemes/create-divi-extension#147]
### Problem Description

Module code: https://pastebin.com/jkCc7qU6

I copied two working text fields, gave them a different variable name, but they do not show up in the back end. All other text fields do.

The two missing text fields are sit_video_1 & sit_video_2.

The module works perfectly, it is simply two text fields that don't show:

```
    function get_fields() {
        $fields = array(
            'sit_video_1' => array(
                'label'           => esc_html__( 'Video URL 1', 'et_builder' ),
                'type'            => 'text',
                'option_category' => 'basic_option',
                'description'     => esc_html__( "What is the URL of your video 1?", 'et_builder' ),
                'toggle_slug'     => 'main_content',
            ),
            'sit_video_2' => array(
                'label'           => esc_html__( 'Video URL 2', 'et_builder' ),
                'type'            => 'text',
                'option_category' => 'basic_option',
                'description'     => esc_html__( "What is the URL of your video 2?", 'et_builder' ),
                'toggle_slug'     => 'main_content',
            ),   
```

### Steps To Reproduce
1. Start with perfectly working module: https://pastebin.com/VzF13C0r

Duplicate
		
```
			'sit_link_1' => array(
				'label'           => esc_html__( 'Link 1', 'et_builder' ),
				'type'            => 'text',
				'option_category' => 'basic_option',
				'description'     => esc_html__( "What URL does this module link to?", 'et_builder' ),
				'toggle_slug'     => 'main_content',
            ),
			'sit_link_2' => array(
				'label'           => esc_html__( 'Link 2', 'et_builder' ),
				'type'            => 'text',
				'option_category' => 'basic_option',
				'description'     => esc_html__( "What URL does this module link to?", 'et_builder' ),
				'toggle_slug'     => 'main_content',
            ),	
```

into

```
			'sit_video_1' => array(
				'label'           => esc_html__( 'Video URL 1', 'et_builder' ),
				'type'            => 'text',
				'option_category' => 'basic_option',
				'description'     => esc_html__( "What is the URL of your video 1?", 'et_builder' ),
				'toggle_slug'     => 'main_content',
            ),
			'sit_video_2' => array(
				'label'           => esc_html__( 'Video URL 2', 'et_builder' ),
				'type'            => 'text',
				'option_category' => 'basic_option',
				'description'     => esc_html__( "What is the URL of your video 2?", 'et_builder' ),
				'toggle_slug'     => 'main_content',
            ),	
```

Find that the new text fields do not display in the back end.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
The "main_content" toggle does not work in the backend builder. You need to create this toggle yourself in init(). Have a look at the examples to see how to add your own toggles.

**Comment by insight47** [comment]
Thanks.

Why does "main_content" work for sit_link_1 & sit_link_2, but not for sit_video_1 or sit_video_2 ?

Where do I find examples please?

**Comment by xxtesaxx** [comment]
Ah sorry, I think I made a mistake. If you are using the demo modules, then the toggle is probably already added. You don't see your fields in the backend builder due to a chaching issue though. If you have a look at the VB you'll see them.

To "fix" this problem you need to run "window.localStorage.clear()" on your browsers JavaScript console. What I normally do is put this JS inside a JS file which my plugin enqueues in the admin area. This way on every page load the localStorage is cleared. Maybe not the most elegant solution but it works :/

**Comment by insight47** [comment]
Thanks, that's excellent. I checked local storage and there was nothing there, and I found my fields were present when editing the module, so cache must of cleared in the mean time.

Cheers.
