### ISSUE TITLE
Builder :: When you add a custom class to a field it displays only on backend

### ISSUE THREAD

**Issue by emilushi** [elegantthemes/create-divi-extension#160]
### Problem Description
When adding a custom class to a new field the custom class is applied to the field only on Backend and not when editing with Visual Builder.

### Steps To Reproduce
1. Create a custom module
2. Add a field using `get_fields()` function
3. On the new field array set a custom class to the field: `'class' => ['custom_field_class']`
4. Save and build the module.

### Screenshot and/or gif
![2018-08-23_19h35_59](https://user-images.githubusercontent.com/3394343/44542039-0d563600-a70c-11e8-814e-8d789f789c20.png)

**Comment by xxtesaxx** [comment]
I'm not sure why you would want to add a class to the settings field (maybe to implement a custom settings field UI?) but there are multiple discrepancies between the VB and the BB. As this is a inoffical API which is not documented it's better to not use it and find another way of targetting your setting. For example via the ID attribute rather than the class. To make it even saver you could prefix your field with your own prefix or see if there is the modules slug somewhere further up in the hierarchy.

Until ET will give us the API to develop custom settings I'd try to stay away from inoffical APIs as much as possible.
