### ISSUE TITLE
Remove wrapper from custom modules

### ISSUE THREAD

**Issue by achchu93** [elegantthemes/create-divi-extension#180]
Currently it is adding a custom wrapper for the element in the backend editor and visual editor. i could manage it to remove the wrapper from backend editor by inheriting parent methos. but from jsx file i couldn't. can anyone please help on this?

**Comment by lots0logs** [comment]
Hi, please see the following comment for more information regarding the wrapper: https://github.com/elegantthemes/create-divi-extension/issues/62#issuecomment-388700752

**Comment by achchu93** [comment]
No, it is not working for visual builder code. i have already mentioned it, that i could manage to do it in php template. but for .jsx template this function doesn't effect. in visual builder again it adds a wrapper.

**Comment by lots0logs** [comment]
Right, I understand that. I'm afraid what you are trying to do is not supported. There is really no reason to mess with the wrapper in the first place. You should code your module in a way that it is contained completely inside the wrapper.

**Comment by achchu93** [comment]
okay, thanks! anyway as i am creating a button i need it much. let see what i can do. is there any events when hover triggered?

**Comment by lots0logs** [comment]
All the normal DOM events are available just like on the frontend :smiley:

**Comment by chaushevic** [comment]
@lots0logs 

The wrappers are added even on child modules (ex. a slider). In your slider which ships with the core plugin the individual slides do not have the "et_pb_module_inner" wrapper, but when making our own they always have it and to an extent, it messes up the slider.

Your own child modules are not wrapped inside this class (because it does not make sense to wrap every slide inside et_pb_module_inner). How do we disable the wrapper for the React component in a case like this?
