### ISSUE TITLE
not able to see preview in visual builder and styles.css not showing

### ISSUE THREAD

**Issue by mrbm** [elegantthemes/create-divi-extension#194]
Hey Guys, just starting out with this, could be operator error...but  I think I've checked everything.

Pulled code yesterday, using divi from today and using fresh ubuntu 18 install from digital ocean as dev environment created yesterday with the latest everything.

yarn start won't work but using npm start will run dev server.

### Problem Description
1. Visual Builder preview of content when using module shows:
`function(t){return r.a.createElement(Dn,oo({rawContentProcesser:se.b.replaceCodeContentEntities},e.props))}`

2. In rendered out mode, the styles.css file is not seeming to be included in the render, however everything else seems to render out without issue.

### Steps To Reproduce
1. Following instructions found here: 

https://www.elegantthemes.com/documentation/developers/divi-module/how-to-create-a-divi-builder-module/

### Screenshot and/or gif
<img width="1157" alt="screen shot 2018-11-15 at 7 58 31 pm" src="https://user-images.githubusercontent.com/391043/48597099-d2c9f700-e910-11e8-9e5b-6bef086b5750.png">

**Comment by mrbm** [comment]
running build gets front end css working, however backend visual builder produces a new error:

<img width="1104" alt="screen shot 2018-11-15 at 9 07 00 pm" src="https://user-images.githubusercontent.com/391043/48599023-c0ed5180-e91a-11e8-8f60-d076d5ac8828.png">

Basing my code off the tutorial code simple header and adding a second field.

**Comment by mrbm** [comment]
https://www.elegantthemes.com/documentation/developers/how-to-create-a-divi-builder-module/ makes reference to:

{this.props.content()}

changing that to:
{this.props.content}
Makes things work, is there a purpose I am missing to having the () or is that a typo?

**Comment by mrbm** [comment]
So I am now learning through more experimentation that:
content()

is not a typo.  Its a reserved statement that allows for a field named content to be defined and then that allows for on screen editing.

My question is this, what if I want a module to have 3 separate fields for on screen editing, is that possible? My attempt to create contentb() with content defined in the array the same as content is what seems to lead to this error in the visual builder.

Thanks!

**Comment by seb-montana** [comment]
Hi,
I have the same trouble... I get function(t){return r.a.createElement(u.a,_({rawContentProcesser:d.default.replaceCodeContentEntities},e.props))} error when VisualBuilder try to render my mymodule.jsx..
Somebody can help me ?
Thanks,

**Comment by Warloxk** [comment]
Hi there, any solution for this?

**Comment by xxtesaxx** [comment]
When you get the function()... output in the VB, you wp-config.php file is missing the debug switch for your module. Often you only need to run yarn start again so it gets added. Make sure your module is in the wp-contents/plugins directory of your wordpress installation. 

The issue with the missing styles from styles.css can be solved by running yarn build so the minified version is created and loaded. Not the ideal case but it works. Alternatively you could put all your styles in the styles.css inside the styles directory though I rather use the first approach since I rarely change the module styles and still like to have them separately for each module.

My dev approach is:

1. Create all the settings in the php module
2. Implement the jsx module including static styles, render and static css(props)
3. Run yarn build to get the static styles on the frontend
4. re-create render() including dynamic styles in php
5. Run yarn build/zip again and pack the module zip

**Comment by coulterpeterson** [comment]
This still appears to be an issue - I'm currently trying to use the module that comes 'out of the box' when I run `npx create-divi-extension my-extension` in side the plugins directory. Same as above, it will render front-end but on the backend I get the r.a.createElement(u.a,_({rawContentProcesser:d.default.replaceCodeContentEntities},e.props))} text displayed instead of the module preview.

One additional step I tried to no avail (because I'm running my WordPress dev site from Flywheel) is adding the 'hot debug snippet' from [this issue thread](https://github.com/elegantthemes/create-divi-extension/issues/5) to the class in my HelloWorld.php file. 

Any assistance or input of any kind is appreciated here.

**Comment by Yohaeni** [comment]
I have a custom module which is made for divi 3.051 version I think...
After update Divi theme, some pages using that module looks crashed (CSS is not working properly)

So I changed "$this->fb_support=false" into "$this->vb_support='on"

After doing that, I can see the message "function(t){return r.a.createElement(f.a, k({rawContentProcesser:se.b.replaceCodeContentEntities},e.props))}"

CSS crashing is still, and I coudn't fix anything... what should I do ToT

**Comment by chrisb34** [comment]
I got this error too but ...

**Instructions from @xxtesaxx above worked for me.**  

You need to do a Yarn build to get the packages built for the frontend builder.  I presume this sets up the basic links to your module and module css, so you only need to rerun the build if you change a static file (like the <your module>/style.css).  

Otherwise, get your code to compile properly with yarn start 

And then do a yarn build.

Develop the rest of your react coding

and then yarn zip when you're ready to deploy (which includes a yarn build)

**Comment by alvarotrigo** [comment]
Or `npm run build` :)

**Comment by lots0logs** [comment]
Tracking this on #69

**Comment by iki789** [comment]
I was able to fix this by doing `yarn start` and while its running, in another therminal do a `yarn build`
