### ISSUE TITLE
Customize existing module

### ISSUE THREAD

**Issue by ghost** [elegantthemes/create-divi-extension#20]
With Divi 3.1 now, do we have a proper way to customize existing modules or is it a bad practice?

**Comment by xxtesaxx** [comment]
Yeah, a way to extend modules, rows and sections would be awesome. For example in Elementor you can add additional settings to each element by using a WordPress actions and filters. A similar technique for Divi would be awesome.

**Comment by richardginn** [comment]
Well web2033 this is like the first version of DIVI where I spotted that all the modules are in separate files instead of one massive 10,000 plus line code filled file.

This would make it easier to attempt it.

**Comment by web2033** [comment]
@richardginn I see in my archive that somewhere around Divi 3.0.84 (October 2017) modules were moved to separate PHP files. But these modules do not have WordPress filters/actions to tweak them safely.

**Comment by lots0logs** [comment]
>With Divi 3.1 now, do we have a proper way to customize existing modules or is it a bad practice?

Its possible to customize official modules, though what's involved highly depends on what exactly you are trying to do. Typically, what you want to do will require taking one of two routes:

### Create a customized version of an official module as a separate module
This is the most common form of customizing official modules. It involves copy the module's PHP class and making it your own. In order to add Visual Builder support to this kind of module you have to create a React Component for it that renders the HTML so that it matches what the PHP render function. 

Some modules require calling special functions in JavaScript to initialize them (like the sliders for example). We're working on documenting those cases. 

### Customize something in an official module without creating a separate module
You can use hooks to customize an official module. Here are some examples:

* `et_pb_all_fields_unprocessed_$slug` - Filters the module's settings definitions
* `et_pb_module_shortcode_attributes` - Filters module's props before its `render()` method is called.
* `$slug_shortcode_output` - Filters the module's HTML output.

We'll be adding official documentation regarding this in the future :smile:

**Comment by richardginn** [comment]
We'll be adding official documentation regarding this in the future 

OH YEAH!!!

**Comment by xxtesaxx** [comment]
Will that work for sections and rows as well?

**Comment by xxtesaxx** [comment]
Awesome, I just gave it a try and it seems to work pretty straight forward. One thing to note though is that in `$slug_shortcode_output` you don't get the props of the module, or do you? Instead I could use `et_module_shortcode_output` and check for the slug before accessing the props:

![image](https://user-images.githubusercontent.com/3000808/39148662-321c0ce6-473d-11e8-9a66-3a80b8879745.png)


![image](https://user-images.githubusercontent.com/3000808/39148859-ac611e74-473d-11e8-87bb-b4562e162e11.png)

![image](https://user-images.githubusercontent.com/3000808/39149445-5831a39e-473f-11e8-9120-fdff3c2e718a.png)

![image](https://user-images.githubusercontent.com/3000808/39149465-66f20964-473f-11e8-9438-33db7b853c60.png)

**Comment by lots0logs** [comment]
Yeah I actually noticed that earlier myself. We should pass the module instance to the callback for the shortcode_output. In the meantime looks like you found a workaround :wink:

**Comment by xxtesaxx** [comment]
Next version, right? ;P

**Comment by web2033** [comment]
So, for example, I want to add more social links to **Person module** (or replace existing links)
Is it possible now to make it using these hooks and without rewriting the module from scratch?

**Comment by richardginn** [comment]
Well Web2033 you could edit the teammmeber.php module and then make a whole new bigger module with more social links in it.

**Comment by xxtesaxx** [comment]
Yes web2033, you can use the hooks and absolutely make that work with the default module 😀

I'm thinking about writing a GDPR extension for the email opt-in to display a GDPR checkbox if it does not get updated within the next weeks but I'm confident ET won't let us hang on this topic xD

**Comment by lots0logs** [comment]
>Yes web2033, you can use the hooks and absolutely make that work with the default module

Indeed :+1: 

>I'm thinking about writing a GDPR extension for the email opt-in to display a GDPR checkbox if it does not get updated within the next weeks but I'm confident ET won't let us hang on this topic xD

That's currently in the works. It'll be ready in time :smiley:

**Comment by dangub86** [comment]
Hi, i'm trying to customize an existing Divi module... following the example by xxtesaxx all is working fine in the default Divi builder and in the final rendering while i don't see the changes in the Visual Builder...

Obviously i think it is because i'm not adding the rendering code in the React component (as we would do it instead if we were creating a new custom module)... so my question is: there is any way to add the React code in order to make it work also in the VB?

**Comment by fedeescalada** [comment]
> In order to add Visual Builder support to this kind of module you have to create a React Component for it that renders the HTML so that it matches what the PHP render function.

Could you please briefly explain how to add a React Component in a child theme? I mean, without creating a Divi Extension?

Thanks in advance.

**Comment by Paul-S-Taylor** [comment]
Designer (not developer) would really like to learn more and see a very simple example of extending one of the current modules using a Child theme and the method above (rather than try to understand a whole module).  Just tried adding a margin-bottom value  to the Blurb Icon using the above hooks. Got as far as the interface slider and being able to pick up the props value. Cant find a way to add a new custom CSS item (icon_margin_bottom)  to the CSS array? (OK probably lack of knowledge) or a way to add VB rendering/React component to the Child theme. So definitely another request for more info when you guys have the time - this opens up so many opportunities for (potentially) simple mods - many thanks

**Comment by Paul-S-Taylor** [comment]
Would it be possible using the above hooks to add another option to the Blurb Image/Icon Alignment array ('icon_placement' => array('options' => $image_icon_placement )). It currently has Top and Left options - wanted to Add Top Left.  I can add new fields to the Builder Interface, but can't see how to append/push a new parameter without overwriting the original.

**Comment by xxtesaxx** [comment]
Can't you get the original setting form the fields_unprocessed or modify them like:

    $fields_unprocessed['name_of_setting']['options']['new_value'] = 'My new Value';
    return $fields_unprocessed;

**Comment by Paul-S-Taylor** [comment]
OK - Apologies for asking here and forgive the ineptitude - but I can't see anywhere else on ET to ask such things and I' really trying to grasp how to do this (appreciate it has been mentioned that docs will be updated in the future ) This is more a learning exercise than anything else - so if any unofficial guidance is available for a non developer -  it is much appreciated. 

In an effort to avoid creating whole modules I've created a Module Mod  in a child theme Functions PHP with a few lines of code  

I have my 2 mods to the Current Blurb Module - that 
1) Modified a current option. Added an option in the icon placement - to Align Top Left 
2) Added a new option. A New option to control the icon margin bottom

Seems to be working

Q1: Is there any way get an idea how the React.JSX should be formed i.e. do you need to match the whole blurb output?
Q2: How do I load the React.JSX from functions.php?

Code so far...
<code>
<?php

add_action( 'wp_enqueue_scripts', 'my_enqueue_assets' );
function my_enqueue_assets() { 
    wp_enqueue_style( 'parent-style', get_template_directory_uri().'/style.css' ); // OK
	wp_enqueue_script( 'Module', get_stylesheet_directory_uri(). '/index.js',array( 'jquery' ) ); // VB code to solve	
}

add_filter('et_pb_all_fields_unprocessed_et_pb_blurb', 'add_module_setting');
function add_module_setting($fields_unprocessed) {
	$fields = [];
		
	$fields['icon_margin_bottom'] = [
		'label' => 'Icon Margin Bottom',
		'type' => 'range',
		'option_category' => 'configuration' ,
		'icon_margin_bottom' => array(
				'label'           => esc_html__( 'Icon Margin to Bottom', 'et_builder' ),
				'type'            => 'range',
				'option_category' => 'font_option',
				'tab_slug'        => 'advanced',
				'toggle_slug'     => 'icon_settings',
				'default'         => '17px',
				'default_unit'    => 'px',
				'default_on_front'=> '',
				'range_settings' => array(
					'min'  => '0',
					'max'  => '100',
					'step' => '1',
					),
					'mobile_options'  => true,
					'depends_show_if' => 'on',
					'responsive'      => true,
				),
			'show_if'         => array(
				'use_icon_font_size' => 'on',
			),
		//// where in the ui
	'toggle_slug' => 'icon_settings',
	'tab_slug' => 'advanced',
	];	
	
// add another option to the current icon_placement select dropdown
	$fields_unprocessed['icon_placement']['options']['topleft'] = 'Top Left';
	return array_merge($fields_unprocessed,$fields) ;
	}

add_filter('et_module_shortcode_output', 'render_item', 10,3);
function render_item($output, $render_slug, $module ) {
	
if('et_pb_blurb' !==$render_slug) return $output;
if ( is_array( $output ) )  return $output; 

$default_icon_margin_bottom = '17px';
$icon_margin_bottom = $module->props['icon_margin_bottom'];
$icon_placement	 = $module->props['icon_placement'];

//print_r ($icon_placement); // test

if ($icon_placement === 'topleft')
	{
	$default_image_icon_placement_css = 'left';
	ET_Builder_Element::set_style( $render_slug, array(
	'selector'    => '%%order_class%% .et_pb_blurb_content',
	'declaration' => sprintf(
					'text-align: %1$s;',
					esc_html( $default_image_icon_placement_css )
				),) );		
	} 
		
if ($icon_margin_bottom !== $default_icon_bottom_margin) 
	{
			ET_Builder_Element::set_style( $render_slug, array(
		'selector'    => '%%order_class%% .et_pb_main_blurb_image',
		'declaration' => sprintf(
					'margin-bottom: %1$s;',
					esc_html( $icon_margin_bottom )
		),) );

	return $output; 
	}	
	
}

</code>

**Comment by Paul-S-Taylor** [comment]
Started going through the basic examples on the ET Dev area again. Making Progress. No problem adding a slider - but  want to add a slider here (see attached). i.e.. so I get an extra control slider added to every H Tag. ![screen_shot](https://user-images.githubusercontent.com/6271748/41689273-bc568da0-74e7-11e8-98fc-52c2b46c6461.png)
How do I do that ?

**Comment by IvanChiurcci** [comment]
Paul-S-Taylor , haven't tried to add in between the existing options but you can add either before or after the options group by adding the `'sub_toggle' => 'H6'` (assuming that the sub_toggle name is H6) to your range option and playing with the `'priority'` key value.

**Comment by Paul-S-Taylor** [comment]
Thanks Ivan - I want to add another slider to to all H tags (the whole tab was added using the get_advanced_fields_config() )

**Comment by Paul-S-Taylor** [comment]
This is not a rant - just the result of many hours of trying to work out how to progress. Have to say, as a designer rather than a developer I'm completely frustrated - put in many hours trying to guess what I should be doing to take things further than the code published on the ET website. Yes I've managed to get a couple of minor things working and get the VB /React scripts functioning, but that's about it so far. I thought that publication of the developer info on the ET blog might enable me to learn how to create something useful or modify existing modules. Yes it most certainly does if you are a developer and know more about the code in the first place, but if not - it seems like a closed world. There isn't anywhere to ask questions or get feedback apart from here on GitHub - which for a non developer is inappropriate,  intimidating and really not the right place to go to learn anything. Is there anywhere we can ask those dumb questions about the API that help you make the leap from code tinkering to something more useful?

**Comment by Paul-S-Taylor** [comment]
@xxtesaxx Thanks for reply. 

Agreed... yes it was a Developer Update ;-)

Appreciate the feedback and yes, if I ever needed a complex Divi extension I would certainly be happy to hire a sub contractor rather than try to figure it all myself.  I'm a designer and that's plenty enough work for me - this is more about personal improvement and learning something new. Running out of places to find information on this subject got a tad frustrating having set myself on that course.

Take Maxon / and its 3D app Cinema 4D - they have http://www.plugincafe.com/forum/default.asp.  If you want to start from scratch - there is a discussion forum and a downloadable API with fully documented code descriptions. Yes the same rules apply - if you want a complex render plugin that does something special - you'd hire a developer that fully understands the API. If you want to do something simple like restrict  the movement of an object in an animation  - you can do it yourself with the information that has been made available. The important thing is - there is lots of information to work with plus somewhere to ask even the the dumb questions.

With ET - the information is limited but more importantly there's no where to officially discuss such things - and that's the biggest frustration. 

Oddly enough, I was looking though the very same file -  class-et-builer-element.php earlier - and spotted the relevant set of labels and sliders. The  $options_settings and  $additional_options arrays are getting  a bit too deep for me to unravel - not impossible - but probably best to go back the the basic examples and take smaller steps from there.

(I'm not expecting it - but if anyone has the time of inclination to show me how to add a slider (for adding padding bottom) to every H type - it would make a very useful reference in making additions to that special collection of pre defined options) 

I hope the ET team put a few more examples online and provide a few more notes on what each items does, as I'm sure there is a place between hiring a developer and a minor tweak.

**Comment by xxtesaxx** [comment]
Alright so here are some hints:

- The headings settings field of the advanced settings font field is of type 'multiple_buttons' so all the settings on there are actually the same. Switching the heading level does not show/hide different settings for each level. Instead the html element in the render function is changed. Here you would only add one slider (and maybe just set the default value based on the selected heading level).
- The settings in Divis core Text module are organised in sub-toggles. There you have multiple settings (e. g. Font) for each heading level. Here you would add 6 sliders, each in its own sub-toggle
- Divis Text module uses the toggle slug 'header' and sub-toggles 'h1' to 'h6' as seen in Text.php 
- To put a setting in a sub toggle you need to set 'toggle_slug' => 'header' and 'sub_toggle' => 'h1' 
- To apply the CSS you can use ET_Builder_Element::set_style as seen in other modules - have a look at the core modules

There might or might not be a unofficial Slack channel for Divi developers to ask questions and get help, to which one can get invited, I heard. But who knows if this is true, right @lots0logs? 😇

**Comment by Paul-S-Taylor** [comment]
@xxtesaxx Thanks again - appreciate the help. I've been getting my head around the sub toggles . Got the ET_Builder_Element::set_style working with a previous test - so its starting to fall into place.

**Comment by Paul-S-Taylor** [comment]
Curious - as it has been mentioned on several occasions - are we going to see any JSX examples from the main builder modules?

**Comment by burhandodhy** [comment]
Divi team should introduce more action/filters and obviously better "Developer" documentation. So we could extend the functionality easily.

**Comment by thelanj** [comment]
Would love to see some simple documentation.  I'm not a legit coder but do well enough and have struggled to build a module for displaying custom posts.

**Comment by PierreBichet** [comment]
So, finally, is it possible to hack an existing module, adding new options and render them in the Visual Builder? Your thoughts @lots0logs? 🙂

**Comment by mortan66** [comment]
Great advice here. Adding fields and taking them into account for the output works well. I need to extend the modules with an UI that goes beyond the standard fields. Is there a way to register new advanced fields where I can define the HTML? Or any other elegant way to include fields with custom HTML? My current approach is to insert the HTML via JS when my custom tab is clicked, but that doesn't feel very clean and creates additional issues with saving and retrieving the entered values. Any advice would be highly appreciated.

**Comment by xxtesaxx** [comment]
I'm afraid this is still not implemented. :(

**Comment by mrkenng** [comment]
Hello guys! Is there a way to get the Font Advanced Fields to work on existing module? I know I can do those fields on my own and render them but to save time writing those again i'm wondering if anyone managed to get that done? Thanks! 

```
$this->advanced_fields = array(
			'fonts'                 => array(
				'body' => array(
					'label'            => esc_html__( 'Body', 'et_builder' ),
					'css'              => array(
						'main' => "{$this->main_css_element} *",
					),
					'hide_text_shadow' => true,
					'block_elements'   => array(
						'tabbed_subtoggles' => true,
					),
				),
);
```

**Comment by Taimoor79** [comment]
Is there any way to a new setting tab in all Divi official module like 
![image](https://user-images.githubusercontent.com/57060906/126945062-9759520a-616f-4fec-9623-0bd8e0c1c889.png)
Thanks in advance.

**Comment by UmerCheema-WPD** [comment]
Hi 
I have a question related to customize existing module.

Suppose i am customizing Text module and want to add custom field before Body how i can add priority ?
Mean First display my custom field then text module body field ?

**Comment by FeIix** [comment]
Hi,
Is it possible to use these hook to override the column_structure of a row module ?

I tried to do it with et_pb_all_fields_unprocessed_et_pb_row (not triggered) and et_pb_module_shortcode_attributes,
but nothing has effect.

```
add_filter( 'et_pb_module_shortcode_attributes', function( $props, $attrs, $render_slug, $_address, $content ) {
    if($render_slug !== 'et_pb_row') return $props;

    if($props['module_id'] !== 'my_test_slug') return $props;

    $props['column_structure'] = '4';
    return $props;
}, 10, 6);
```

Is the doc available somewhere ?

**Comment by r-interactive** [comment]
Anyone have a solution to render the custom field value (such as the css style) in the Visual Builder? 
I am getting this warning message: This option is not previewable in the Visual Builder (screenshot: https://snipboard.io/uB6P9R.jpg)
