### ISSUE TITLE
Inner Modules

### ISSUE THREAD

**Issue by gonzalesc** [elegantthemes/create-divi-extension#213]
Hi
Im doing a module to show any module if the user is logging.
Then I need put a module allows put any module inside.

is it possible?

**Comment by xxtesaxx** [comment]
Not directly. The only way to put modules inside modules is to create a layout somewhere else and load it into your module. Take for example the Library Layout module from the Battle Suit for Divi plugin: https://wordpress.org/plugins/ds-suit

The module allows you to display a layout which is saved in Divis Layout Library

**Comment by gonzalesc** [comment]
Ok. Really, It is not I want.
I will take my plan B and I need to add fields to secction module, a checkbox "show if the user is login", but I dont found any filter to I can add custom fields.

Do you have some suggest?

Regards

**Comment by xxtesaxx** [comment]
Ah, so you want to add a switch on a section to hide that section if a user is not logged in? That is absolutely possible using filters. Check out this issue with my comment: https://github.com/elegantthemes/create-divi-extension/issues/20#issuecomment-383698880

Basically you just have to check if the prop is on and if so, instead of returning the output, only return it if the user is logged in. There is a wordpress function is_user_logged_in() or so which you could use.

**Comment by gonzalesc** [comment]
Ehh cool !
Well I used the first hook and my field is strange:

![image](https://user-images.githubusercontent.com/2523478/50792297-36362c80-12a3-11e9-8814-8fb6a5993821.png)

But well, I will continue investigating. Thanks!

**Comment by xxtesaxx** [comment]
Looks like your field definition is not correct. Can you post it?

**Comment by gonzalesc** [comment]
Hi. Ok it was my error.. it works! Thanks.

A question, I need to create a new tab in the section module. Existe some hook?

![image](https://user-images.githubusercontent.com/2523478/50833260-61665d80-132f-11e9-827e-831367642c70.png)

I think I must create a new tab_slug and a new toggle_slug .

Regards

**Comment by gonzalesc** [comment]
Ok I found "et_builder_main_tabs" cool !
Now Im seeing how put a subtitle inside the new tab.. I think it is call modal toggles

**Comment by gonzalesc** [comment]
I saw it was creating by $this->_add_settings_modal_toggles()
