### ISSUE TITLE
Docker Development Environment Setup Failing - Bad WP Release/Version

### ISSUE THREAD

**Issue by zlanich** [elegantthemes/create-divi-extension#241]
### Problem Description
The Docker Environment setup fails due to a specified WP version that WP CLI doesn't seem to recognize.

### Steps To Reproduce
1. Follow exact setup instructions in these docs: https://www.elegantthemes.com/documentation/developers/divi-development-environment/

### Screenshots & Details

http://zsl.io/LLbJiE

It doesn't seem to like the 5.1.0 version. I was able to get it to install by doing an export WP_VERSION=5.1.1 before running it

**Comment by zlanich** [comment]
Hey @lots0logs, is it safe to assume that you closed this because it's fixed?

**Comment by lots0logs** [comment]
![yup](https://media.giphy.com/media/l0MYwvNiMaWJhQZjy/giphy.gif)

**Comment by zlanich** [comment]
My hero. 🥳


Best Regards,

Zach Lanich
*Business Owner, Entrepreneur, Creative*
*Owner/CTO*
weCreate LLC
*www.WeCreate.com <http://www.WeCreate.com>*

From: Dustin Falgout <notifications@github.com> <notifications@github.com>
Reply: elegantthemes/create-divi-extension
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 29, 2019 at 4:47:16 PM
To: elegantthemes/create-divi-extension
<create-divi-extension@noreply.github.com>
<create-divi-extension@noreply.github.com>
CC: zlanich <zach@zachlanich.com> <zach@zachlanich.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [elegantthemes/create-divi-extension] Docker Development
Environment Setup Failing - Bad WP Release/Version (#241)

[image: yup]

**Comment by lots0logs** [comment]
![lol](https://media.giphy.com/media/oFeUVZfiuim9G/giphy.gif) 

lol ;-)

**Comment by reepicheep05** [comment]
Hey guys, just to let you know, this bug is not resolved.  Getting the same error now.

Thanks to zlanich for his workaround

Running "export WP_VERSION=5.1.1" before the "divi-dev setup" command did work for me. 

---

etdev@divi-dev:/workspace/wordpress$ export WP_VERSION=5.1.1
etdev@divi-dev:/workspace/wordpress$ divi-dev setup
Downloading WordPress 5.1.1 (en_US)...
md5 hash verified: e878b33b520f61e61f2caa0f08886c1b
Success: WordPress downloaded.
Initializing database...  ██████████████████████████████| 100%
Success: Generated 'wp-config.php' file.
Success: WordPress installed successfully.
Success: Rewrite rules flushed.
Success: Rewrite structure set.

Setup Complete! Here's how you can access WordPress:

URL:       http://local.divi-dev.site
Username:  divi-dev
Password:  password

etdev@divi-dev:/workspace/wordpress$ 

---

Maybe you could add that tip to the divi instruction page for future users in case the Wordpress 5.1.1 image becomes unavailable in the future. 

https://www.elegantthemes.com/documentation/developers/divi-development-environment/

Thanks to both of you!
