### ISSUE TITLE
The computed fields are no longer rendered in the VB

### ISSUE THREAD

**Issue by capellopablo** [elegantthemes/create-divi-extension#280]
### Problem Description
I have some troubles with de new Divi update (v3.25 to 3.26).

My modules with computed props are no longer rendered in VB.
If i change some field value (´computed_affects´) the build dont proccess the changes, I have to save, and reload it.
When i create a new module in VB react always return undefined for computed props on componentDidMount().
I cloned the Divi Blog module changing the slug without success.
If I do a rollback version to 3.25 its work.

Is someone else having similar problems? What change in this version?
How can i use computed props and computed_affects?

### Steps To Reproduce
1. Use computed_affects for a computed field

### Screenshot and/or gif
____
### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/6192

**Comment by robertJurinek** [comment]
I am suffering from the same issue. This is very serious bug since all the custom modules which are using `computed` fields stopped working with newest VB now. 

I did some javascript debugging using Divi versions `3.25.3` and `3.26.3`. 

## My Findings
1. Javascript in `includes/builder/frontend-builder/build/bundle.js` is(was) responsible for running timeouted AJAX request after any field from `computed_affects` is updated.
2. In version `3.25.3` a function (`function ji(t, n, o, r)`) which executes AJAX request with `action: "et_pb_process_computed_property",`  is being run on 6 various places in code which are (from what I was able to deduce from obfuscated code) responsible for various events, one of them is change on field values which affect computed fields in custom modules. 
3. In version `3.26.3`  a function (`function Fi(t, n, o, r)`) which executes AJAX request with `action: "et_pb_process_computed_property",` is present, but is nowhere in code being run. I believe non existing event listeners for custom fields which are inside `computed_affects` are responsible for this bug. 
4. The computed fields of built-in Divi modules are still working.

## Possible Temporary Fix
Very ugly possible fix is setting `public $vb_support = 'partial';`. 
This will make module recomputed on each input change, but this also leads to the nasty message:
> "This third party module is not fully compatible with the latest version of the Divi Builder."

I suggest to use this for development purposes only. I hope developers of Divi will provide a fix to their Visual Builder ASAP.

**Comment by capellopablo** [comment]
Hi Robert.

Thanks for share. I was working on this about a week.
You have done an amazing investigation. Hopefully we have news soon, I have my developments totally stopped by this.

**Comment by mrkenng** [comment]
I'm having the same issue where computed field stopped working after 3.26

**Comment by Jronk** [comment]
The fix has been merged and will be included in the next release. 👍

**Comment by Wolic** [comment]
> The fix has been merged and will be included in the next release. 👍

Can you provide information when the next fix will be released?

**Comment by mrkenng** [comment]
fixed in the latest divi.

**Comment by Wolic** [comment]
> fixed in the latest divi.

Mh, is it also fixed in the EXTRA Theme? There I still have the bug with the current version 2.26.5 , but not in 2.25.3.

**Comment by lots0logs** [comment]
From Divi Devs Slack:

Maciej  5 hours ago
>@Dustin Divi 3.26.6 brings back module rendering however options still don't work. There must be some bug with computed fields. Can you confirm @Jan Thielemann? (edited)

Maciej  5 hours ago
>All modules were working great before version 3.26 (edited)

Jan Thielemann  5 hours ago
>Yes, I can confirm this. My masonry gallery now loads the html but it still does not work as it did before

**Comment by dm-chechik** [comment]
In order to support the Global Defaults editor the method of how the computed fields are passed to React component has been slightly changed. That might affect to modules using DOM manipulating libraries to display the module content. For example libraries creating sliders or masonry views etc.
In Divi versions prior to **3.26** the computed fields were available right at the moment of mounting a React component so most of the modules that I tested use approximately following code within the **componentDidMount** method
```
.......
// Get DOM element to use it while initialization any library
const grid = ReactDOM.findDOMNode(this.refs.grid);

// Initialization
this.gridMasonry = $(grid).masonry({
   ... some initialization parameters
});
.......
```
Now the computed fields are fetched after component mounting and they are available on the next rendering cycle. So to handle this you need to move the initialization code over to the **componentDidUpdate** method
```
componentDidUpdate(prevProps) {
  // Initialization/re-initialization should be done only if computed fields has been changed
  if (prevProps.__your_computed_field !== this.props.__your_computed_field) {
    // Get DOM element to use it while initialization any library
    const grid = ReactDOM.findDOMNode(this.refs.grid);

    // Initialization
    this.gridMasonry = $(grid).masonry({
       ... some initialization parameters
    });
  }
}
```

**Please note the above changes might be incompatible with the Divi versions prior to 3.26**

Our apologies for the inconvenience. Please do not hesitate to ask any questions.
