### ISSUE TITLE
How to access the current post $post object in "computed" field type callback?

### ISSUE THREAD

**Issue by SailorAbood** [elegantthemes/create-divi-extension#32]
I have a custom module with a computed field, as far as I understand, computed fields render their content in the visual builder using ajax by calling the "computed_callback" method, see Divi built-in Blog module for reference. 

The issue I'm facing right now is that I NEED the current post's - where the module is used - $post but it always returns null, other functions also are not working like get_the_ID(), $GLOBALS['post'] and pretty must any function that needs the current post ID as a parameter.

This is because the "computed_callback" method is being called in admin-ajax.php without passing the current post id or something.

- Is there a way to get that $post object? 

- I couldn't find any documentation about the computed fields, so please update the documentation.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by VladET** [comment]
@SailorAbood We have the `get_the_ID()` method that you can pass in `get_post()`. A quick example:

```$post = get_post( $this->get_the_ID() );```

Let me know if that helps.

**Comment by SailorAbood** [comment]
@VladET Thank you! this is great, I didn't know this method exists.

One more thing please, the output of the combuted_callback method is an HTML form - add to cart form - but it gets escaped in the visual builder, see this screenshot
https://test.abdozo.com/wp-content/uploads/2018/04/Screen-Shot-2018-04-26-at-12.03.05-PM.png

Why is this happening?

**Comment by lots0logs** [comment]
In order to use raw HTML in a React Component you have to do it like shown [here](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml). Let me know if you have any further questions about it :smiley:
