### ISSUE TITLE
Custom module icon only used in VB

### ISSUE THREAD

**Issue by haedworm** [elegantthemes/create-divi-extension#33]
### Problem Description
Adding a custom svg for a module icon works in the Visual Builder but the BB still shows the default font icon, is there a way to add it to both?

### Steps To Reproduce

            $this->icon_path        =  plugin_dir_path( __FILE__ ) . 'icon.svg';

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
Since I want my modules to pop out a bit more so users can immediately distinguish them from core modules, I use my own CSS rather than just relying on the icon path. For that you need two CSS locations. For the backend builder, you put it in your admin.css:

    .et-pb-all-modules .et_pb_jt_counter:before,
    .et_pb_saved_layouts_list .et_pb_jt_counter:before {
      content: "\58";
    }
    
    .et-pb-all-modules .dss_post_meta_parent:before,
    .et_pb_saved_layouts_list .dss_post_meta_parent:before {
      content: '\70' !important;
      font-family: 'ETmodules';
    }
    
    .et-pb-all-modules .et_pb_jt_counter,
    .et_pb_saved_layouts_list .et_pb_jt_counter {
      background-color: #3949ab;
      color: white;
    }
    
    .et-pb-all-modules .et_pb_jt_counter:after,
    .et_pb_saved_layouts_list .et_pb_jt_counter:after {
      content: url('../divi-sensei-64.png');
      position: absolute;
      top: 6px;
      right: 0px;
    }

For the visual builder, you put the CSS inside the modules own CSS file (as it is loaded on the frontend, not the admin area):

        .et-fb-all-modules .dss_post_title:before {
            content: '\61' !important;
        }
    
        .et-fb-all-modules .dss_post_title {
            background-color: #3949ab;
            color: white;
            overflow: visible;
        }
    
        .et-fb-all-modules .dss_post_title:after {
            content: "";
            background-size: 40px 40px;
            background-image: url('./../../../admin/assets/divi-sensei-64.png');
            background-repeat: no-repeat;
            position: absolute;
            top: -10px;
            left: -15px;
            width: 40px;
            height: 40px;
        }

**Comment by haedworm** [comment]
Thanks for this. I have been doing much the same with the Admin CSS already but it didn't even occur to me to use the Module CSS for the Visual Builder. That's good to know.
