### ISSUE TITLE
Filter "wp_insert_post_data" causes Visual Builder saving to fail

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#42]
### Problem Description
I have a module in which the user can select a post id. I don't want to allow selection of the current post but "get_the_ID" does not return the current post in `add_fields()` so I implemented the filter `wp_insert_post_data`. In the callback I use regex to look for the post_id and remove it if it matches the current post like so:

    add_filter( 'wp_insert_post_data', 'dss_sanitizy_post', 10, 2 ); 
    function dss_sanitizy_post( $data, $postarr ) {
        $post_id = $postarr['ID'];	
        $search  = "\[dss_library_layout([^\]]*)post_id=." . $post_id . ".([^\]]*)\]";
        $replace = "\[dss_library_layout$1$2\]";
        $data['post_content'] = preg_replace($search, $replace, $data['post_content'] );
        return $data;
    }

When I now save in the VB, I get this error:

`
An error has occurred while saving your page. Various problems can cause a save to fail, such as a lack of server resources, firewall blockages, plugin conflicts or server misconfiguration. You can try saving again by clicking Try Again, or you can download a backup of your unsaved page by clicking Download Backup. Backups can be restored using the portability system while next editing your page.

Contacting your host and asking them to increase the following PHP variables may help: memory_limit, max_execution_time, upload_max_filesize, post_max_size, max_input_time, max_input_vars. In addition, auditing your firewall error log (such as ModSecurity) may reveal false positives that are preventing saves from completing.

Lastly, it is recommended that you temporarily disable all WordPress plugins and browser extensions and try to save again to determine if something is causing a conflict.
`

![image](https://user-images.githubusercontent.com/3000808/39397020-bc0af55c-4af8-11e8-9660-074090bb2ce9.png)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
You can find an example of getting the current post from your module's PHP code [here](https://github.com/elegantthemes/create-divi-extension/issues/32#issuecomment-384585342). Let me know if that helps.

**Comment by xxtesaxx** [comment]
Oh yeah right. Thats how you can get the post id but still the settings seem to be cached:

![image](https://user-images.githubusercontent.com/3000808/39400718-3225e9b2-4b36-11e8-8dbd-03c027a905db.png)

![image](https://user-images.githubusercontent.com/3000808/39400725-5a95cba6-4b36-11e8-86d1-b343da4b385f.png)

Furthermore it would be possible to select the post on another page, then save it to the library and import it on the post with that ID. Thats why it is important to sanitize the ID. 

I reduced the example even more and this already causes the error: 

    add_filter( 'wp_insert_post_data', 'dss_sanitizy_libray_item', 10, 2 ); 
    function dss_sanitizy_libray_item( $data, $postarr ) {
        $data['post_content'] = $data['post_content'] . "test";
        return $data;
    }

**Comment by lots0logs** [comment]
Sorry, could you explain a bit more at a high level what it is exactly you are trying to achieve. Like what result are you trying to make possible for the end user.

**Comment by xxtesaxx** [comment]
That first answer was for the issue xD

About this one: In my module I have a post_id field where the user can select a post. I want to prevent them from selecting the current post (the one where the module is used on). However, you could copy the module from another page or load it from the library (where the current post was selected previosly). I want to prevent that by sanitizing the post before it is saved to the database. The wp_insert_post_data was suggested for that and in the backend, this works fine. However, on the Visual Builder this somehow causes the aforementioned error.

**Comment by lots0logs** [comment]
It seems like it would make more sense to check to see if the saved post_id is the same as the one the module is being rendered on when you are rendering the module (and bail out of rendering if it is the same). No?

**Comment by lots0logs** [comment]
Is that the exact regex pattern you are using when the issue occurs?

**Comment by xxtesaxx** [comment]
Yes but check out the second answer. Even appending "test" to the content causes the error:

    $data['post_content'] = $data['post_content'] . "test";

**Comment by lots0logs** [comment]
>Yes but check out the second answer. Even appending "test" to the content causes the error:

That is expected. The builder compares the post content from database after save completes to the content it saved and if it's different, the save is considered to have failed (even though technically it didn't fail).

I'll dig into this deeper on Monday and get back to you..

**Comment by xxtesaxx** [comment]
Ah that would be awesome. Or do you maybe know another way of altering the content before saving?

**Comment by lots0logs** [comment]
For now you can put this inside the callback where you are altering the post content:

```php
add_filter( 'et_fb_ajax_save_verification_result', '__return_true' );
```
