### ISSUE TITLE
create-divi-extension :: Child item HTML is malformed

### ISSUE THREAD

**Issue by BoDonkey** [elegantthemes/create-divi-extension#43]
### Problem Description
I am writing an extension with the ability to add multiple child elements to the parent element. I noticed that the HTML output double wraps the child item in two sets of identical divs. This is also the case with the parent/child custom CTA from the divi-extension-example.

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/13168224/39402029-e2d4a74e-4b22-11e8-955f-0ab14a9952d8.png)
![image](https://user-images.githubusercontent.com/13168224/39402033-faf3a8d4-4b22-11e8-9da8-4ba76f5d867c.png)

In the second image, you can see that the divs with classes of 'dicm_cta_child_0' and 'et_pb_module_inner' class are repeated - with the second set nested inside the first. I wasn't aware that the child items would be wrapped this way at all. I can see it causing some problems with both CSS and DOM traversing in jQuery adding in items that are outside of what has been coded in the module.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
Thanks for the report. We'll take a look at it and get a fix out next week.

**Comment by xxtesaxx** [comment]
I also noticed that when you restore a previous state in the VB, the et_pb_module_inner class is missing in the childs wrapper so you end up with a div with no class.

**Comment by jcdotnet** [comment]
Same here, a div element with the child module classes and another div element with the class et_pb_module_inner are rendered with every item when vb_support is 'on'.

These aditional wrappers break the entire module. Any workaround while it is fixed? If so, please share so we can adapt our modules to the new Divi API. Thanks in advance! JC

**Comment by jcdotnet** [comment]
Found this in the ET_Builder_Element class:
```
// Wrap 3rd party module rendered output with proper module wrapper
		// @TODO implement module wrapper on official module
		if ( 'on' === $this->vb_support && 'render' === $render_method && ! $this->_is_official_module ) {
			$output = $this->_render_module_wrapper( $output, $render_slug );
		}
```
If the vb_support is set to 'on' the wraper classes are added so this issue has nothing to do with the create-divi-extension, this is how it works for all the modules since Divi 3.1. The new question is: 

Should we change our HTML rendering to meet this?? I would like to render my child modules like I always did (without these wrapers) and like the official modules currently does (see the Tab / TabItem output). 

This is a very important change, please support, thank you again.

**Comment by MarieComet** [comment]
Also noticed that, a simple fix : replace `return $this->_render_module_wrapper( $output, $render_slug );` in https://github.com/elegantthemes/divi-extension-example/blob/master/includes/modules/CustomCtaChild/CustomCtaChild.php#L180 with `return $output;`
For now I don't see any issue doing this replacement.

**Comment by lots0logs** [comment]
@MarieComet Thanks for noticing that! Looks like the example extension wasn't updated when we moved the call to that function up into Divi's code instead of in the extensions :man_facepalming:
