### ISSUE TITLE
Parent-Child Module issues in Visual Builder: How to insert stuff between renderings

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#45]
### Problem Description
1. In the settings panel of the VB, the child item titles are not shown
2. What is the VB equivalent of before_render / how to send information back from the child to the parent

I have a module where users can add multiple childs. Each child in PHP is not rendered. Instead I use before_render() to create a global array

    public function before_render() {
        global $items;
        $items = array();
    }

In each child I append the child to that array. I do this because in the parent I need to add HTML between each item.

I checked the module props and it seems that in the parent I could access child props by using 

    this.props.content[0].props.attrs.my_child_property

Is that the intended way when child items do not get rendered using `{this.props.content}`? This would mean my parents react component would also contain all the code for rendering the child, right?

### Screenshot and/or gif

Backend Builder: 

![image](https://user-images.githubusercontent.com/3000808/39404884-b993d390-4b9b-11e8-8483-846591958056.png)

Visual Builder: 

![image](https://user-images.githubusercontent.com/3000808/39404888-c354239e-4b9b-11e8-86ed-b26f434f792c.png)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
After a day of working I just recognized how stupid I was. Of course the parent `this.props.content` is the array which contains the rendered childs. I simply can iterate over this array and insert the items as well as the html in between into a new array and then render the new array in the parent.
