### ISSUE TITLE
example with this.props.attrs?

### ISSUE THREAD

**Issue by odoremieux** [elegantthemes/create-divi-extension#52]
An example with this.props.attrs would be awesome.
How are you using the WP object with JSX?
Are you using propTypes? If yes how?

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
>An example with this.props.attrs would be awesome.

I'm not sure what you mean? 3P Modules do not have access to `this.props.attrs` because its contents is hoisted up into `this.props`.

>How are you using the WP object with JSX?

Could you provide more details? What is it exactly you are wondering how to accomplish?

>How are you using the WP object with JSX?

Yes and no. We do use them but not consistently. We've found that they don't make much of an impact on our development workflow. More often than not they are a chore.

**Comment by odoremieux** [comment]
In several places in bundle.js there is 
this.props.attrs.module_class
this.props.attrs.text_orientation
this.props.attrs.module_id
this.props.attrs.admin_label
this.props.attrs.title
this.props.attrs.content

so I'm wondering how you assign attrs to this.props

**Comment by lots0logs** [comment]
I see. Well, as I explained above, that is not exposed to 3rd party modules. All the attrs are available to you under `this.props`.

**Comment by odoremieux** [comment]
So how are you getting the page title or permalink from a page_id in JSX?
Like the equivalent of get_the_title($page_id), get_permalink($page_id) ?

**Comment by lots0logs** [comment]
We send that data down when the builder loads using wp_localize_script(). We're planning to expose that data via the API as part of addressing https://github.com/elegantthemes/create-divi-extension/issues/23
