### ISSUE TITLE
Better Documentation:: get_advanced_fields_config()

### ISSUE THREAD

**Issue by BoDonkey** [elegantthemes/create-divi-extension#56]
### Problem Description
I am currently writing a module where I am adding two sections of text - a header and some body content. I want to have two sections under the design tab for controlling the font settings of each block of text. I wrote two arrays, one for the header, and one for the body and it works wonderfully, except that there is also a section that just displays with the label 'Text' that proceeds these two sections, that contains settings for text orientation and shadow. I tried adding 
    'text_orientation' => false
    'text_shadow' =>false
But, no luck. 
In a child module I have a similiar odd problem. I have added three additional options for setting colors through the 'get_fields' function. I then wanted to be able to alter the font settings and box shadow for one item, without any other settings. I used the following code:
```php
public function get_advanced_fields_config() {
		return array(
			'background'		=> false,
			'border' 			=> false,
			'box_shadow'		=> array(
				'default'		=> array(
					'css'		=> array(
						'main'  => "%%order_class%% .timeline-panel",
						'important'	=> 'all',
					),
				),
			),
			'button'			=> false,
			'filters'			=> false,
			'fonts'				=> array(
				'text_orientation'	=> false,
				'text_shadow'		=> false,
				'node_text' => array(
					'label'    => esc_html__( 'Node', 'et_builder' ),
					'css'      => array(
						'main' => "{$this->main_css_element} .timeline-badge .timeline-text",
					),
					'font_size' => array(
						'default' => '30px',
					),
					'letter_spacing' => array(
						'default' => '0px',
					),
					'line_height' => array(
						'default' => '2em',
                    ),
					'hide_text_color'   => true,
					'depends_show_if' => array(
						'badge_type' => 'text',
					),
				),
			),
			'margin_padding'	=> false,
			'max_width'			=> false,
		);
	}
```
for the get_fields function I have (in addition to the other fields):
```php
'box_background_color'  => array(
				'label'             => esc_html__( 'Box Background Color', 'diti-divi-timeline' ),
				'type'              => 'color-alpha',
				'custom_color'      => true,
				'tab_slug'       => 'advanced',
				'toggle_slug'		=> 'box_colors',
			),
'title_text_color' => array(
				'label'             => esc_html__( 'Title Text Color', 'et_builder' ),
				'type'              => 'color',
				'custom_color'      => true,
				'tab_slug'          => 'advanced',
				'toggle_slug'		=> 'text_colors'
			),
'content_text_color' => array(
				'label'             => esc_html__( 'Content Text Color', 'et_builder' ),
				'type'              => 'color',
				'custom_color'      => true,
				'tab_slug'          => 'advanced',
				'toggle_slug'		=> 'text_colors',
			),
```
This results in the three get_fields being displayed correctly first. Then I get a truncated text settings with orientation and shadow, and then two additional full text settings boxes, before my 'Node Text' settings that only contains text alignment and shadow. See GIF below.
I guess I'm looking for a little clarification on how to properly code this section. As a bonus- can I make the node text settings only appear when a specific field has the value of 'text' on both the back-end and VB, or is this only for VB?

### Screenshot and/or gif

![screen](https://user-images.githubusercontent.com/13168224/39811009-54b12e98-5355-11e8-8852-e90a32cbaac8.gif)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [x] Helpful title used
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by BoDonkey** [comment]
Thanks, that did it for removing the unwanted sections! 
Two questions - 1) Any thoughts on getting the rest of the fonts options turned on in the 'Node Test' region? 2) Where did you find the 'text' option for get_advanced_fields_config? Been trolling through the Divi code to try and identify all of the possible config fields.

**Comment by haedworm** [comment]
I thought most of the font options were on by default, I don't have anything much different than your node_test array for adding additional font settings. Do you have a toggle set for the node_text field? It's not required afaik but if you have one incorrectly named, or an extra toggle not used it might mess things up. I'm almost certain I've encountered a similar issue.
Sadly, I never really found the 'text' option, that was pure trial and error (or guesswork and luck).

**Comment by BoDonkey** [comment]
Cheers! Trial and error it is.

**Comment by lots0logs** [comment]
You should only include keys in the fonts array for elements that you want font settings to be shown for. Basically if you remove the two keys that you set to false inside the fonts array it should resolve your issue. Let me know if you have any questions :)

**Comment by naveed520** [comment]
I'm having the same problem I'm trying to configure button advanced setting to hide icons but did't get any thing Here is my button advanced configuration code
`
               

         public function get_advanced_fields_config() {
                     return array(
			
            'button'         => array(
                'view_more' => array(
                    'label'         => 'View more button',
                    /* 'css'           => array(
                        // 'plugin_main' => "{$this->main_css_element} .act-post .et_pb_button_wrapper a.et_pb_button",
                        // 'alignment'   => "{$this->main_css_element} .act-post .et_pb_button_wrapper",
                    ), */
					
                    // 'use_alignment' => true,
                    'box_shadow'    => false,
                    'show_button_icon'    => false,
                    'button_icon'    => false,
                    'icon'    => false,
                ),

            ),
			
			);
    }
`


what I'm dong wrong ? ? @lots0logs

**Comment by lots0logs** [comment]
@naveed520 Try this:
```
<?php

public function get_advanced_fields_config() {
                 return array(
		
        'button'         => array(
            'view_more' => array(
                'label'         => 'View more button',
                /* 'css'           => array(
                    // 'plugin_main' => "{$this->main_css_element} .act-post .et_pb_button_wrapper a.et_pb_button",
                    // 'alignment'   => "{$this->main_css_element} .act-post .et_pb_button_wrapper",
                ), */
				
                // 'use_alignment' => true,
                'box_shadow'    => false,
               'hide_icon' => true,
            ),

        ),
		
		);
}
```

**Comment by naveed520** [comment]
@lots0logs Currently I'm trying to override its button Custom styling . . . I'm trying your option and than I'll let you know

**Comment by naveed520** [comment]
@lots0logs  You Saved my Whole day... It works. Where did you get button settings ? ?  ? I've searched all from Divi Documentation but did not got anything

**Comment by lots0logs** [comment]
I had to check it directly in the source. All advanced fields are generated inside `class-et-builder-element.php`

**Comment by naveed520** [comment]
In which file this class exist   ?  ? ?

**Comment by naveed520** [comment]
ok I got the file (: Thanks

**Comment by lots0logs** [comment]
@naveed520 Btw, we have a Slack workspace for 3rd-Party Divi Devs. You can join it using this form: https://docs.google.com/forms/d/e/1FAIpQLSfe_iclu50e5laCcfdzsS1NR4KKqnvyFRWCRPLHkEUtdIPPYQ/viewform

**Comment by naveed520** [comment]
ok I've joined that group and now when I'll got approve

**Comment by naveed520** [comment]
ok we can ask questions in channel  ???  or create new channels along with new question :P

**Comment by lots0logs** [comment]
Questions in the main channel :)
