### ISSUE TITLE
Module output

### ISSUE THREAD

**Issue by jamesfosker** [elegantthemes/create-divi-extension#62]
Is there a way to not output the 2 module div that are added by default, the following Divs

```
1. `<div` class="et_pb_module hello_world hello_world_0">
2. <div class="et_pb_module_inner">
```
I am building a module which works differently and those divs end up being extra code which is not needed.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by jamesfosker** [comment]
Sorry the previous post has been adjusted as the div name were not displaying.

**Comment by ketanshah79** [comment]
Just add this to your divi module class

~~~~~
protected function _render_module_wrapper( $output = '', $render_slug = '' ) {
	return $output;
}
~~~~~

The divi element class which is parent to all the modules adds these inner divs in its `_render_module_wrapper` function. By overriding that function, you can control its behavior.

Regards

**Comment by lots0logs** [comment]
We strongly recommend that you not alter the wrapper. Of course, ultimately it's up to you but please note that we can only support modules that use the proper wrapper structure. If you run into any problems, which is very likely btw, you'll be on your own.  Just fyi, we  will be migrating all of our official modules to the new structure as well in the coming months.

**Comment by jamesfosker** [comment]
@ketanshah79 thanks for that :), @lots0logs I understand why you would recommend that but for this particular use case I don't require those divs as they add extra code bloat as I just need a single div to achieve what I want, all my other plugin are fine to use the standard code but this plugin has an alternative use for the modules.

If you don't want developers to change the wrapper structure maybe look at creating an alternative way  to remove those containers divs

**Comment by dreamcoder8** [comment]
Hello,

How do remove that wrapper from JSX?

Thanks
Hitesh

**Comment by mhimon** [comment]
@dreamcoder8 hi, how did you remove the wrapper from JSX?

**Comment by dreamcoder8** [comment]
@mhimon - Hi. No, I didn't.
