### ISSUE TITLE
Yarn issue: port already allocated

### ISSUE THREAD

**Issue by dangub86** [elegantthemes/create-divi-extension#66]
### Problem Description
I've set up the Divi development environment as described in the Developers documentation. Then i've created a Divi Extension and trying to add a custom module. I followed all the steps for adding modules but when i try to execute the command 'yarn start' it gives me the screenshot below saying that something is already running on port 3000 (obviously on the port 3000 is already running the docker containers i created following the "Divi Development Environment Setup" tutorial!)

Furthermore, if i don't run yarn and try to customize the SimpleHeader module i get some cache related issue (i suppose...)... i can't see the changes i do in the php file just refreshing the page. Can it depend from the 'yarn' problem?

### Screenshot
![screen-yarn-issue](https://user-images.githubusercontent.com/32620829/40127628-1b6c9cc2-5930-11e8-824e-cad0ac62e3ef.jpg)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
Hi, you need to run the command from inside the docker container :smile:

**Comment by dangub86** [comment]
Hi, thanks for the reply... I know the question seems stupid (it is) but I'm a newbie about Docker :( ... basically once I've the Docker running and run the command "cd [path-to-my-plugins-directory]" on the terminal which command have i to run in order to start Yarn? Something like "docker-compose run yarn start"? I'm trying but nothing :(

**Comment by lots0logs** [comment]
First you have to enter the container using `docker-compose exec -u 1000 wordpress /bin/bash` then you change to your plugin's directory and run `yarn start`. You can find a quick reference for common commands used to work with the container in our documentation [here](docker-compose exec -u 1000 wordpress /bin/bash). Let me know if that helps :smiley:

**Comment by The1nternet** [comment]
This detail should be added to the documentation.  I didn't know the command had to be called from inside the container causing me to waste some time. Since the documentation describes setting up the environment, then the part that describes calling `yarn start` should mention this detail.
