### ISSUE TITLE
Dreamweaver CC on Mac / PC

### ISSUE THREAD

**Issue by randomblink** [elegantthemes/create-divi-extension#7]
I am a Dreamweaver User for all my development. I go back and forth between a PC and a Mac and would like to know what is needed to create Divi Modules using Dreamweaver...? Or is this strictly for other IDE's?

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
Hi, you can use any IDE that you like to develop Divi extensions with custom modules :smiley:

**Comment by randomblink** [comment]
Forgive my ignorance... I've never developed for Wordpress before. I've done development for other CMS's but with Wordpress I've primarily stuck with Divi-based layout development and plugin configurations. So when 3.1 Divi came out I decided I needed to go ahead and dive in. I have custom modules I've wanted and now if I just learn the Wordpress/Divi development process then I can start to make these come to life.

So everything I have read (and I've read the entire ET Developer Documentation) appears to require that I install Dockers(?) and run command-line commands in order to compiled(?) my module development environment.

What I remember about PHP, and what I know about JS and HTML5 is that they don't need to be compiled. So I am very confused about where I would start out with Dreamweaver.

For instance... my first thought is to just clone the repository, dump the code into my plugin folder on a test/staging Wordpress install with Divi installed, and start testing... But then I see the *.jsx file and I'm lost. Does require preprocessing? How would I do this in Dreamweaver?

My current experience is with a Dojo environment use an API created for webmaps by ESRI, interspersed with HTML/JS/CSS coding here and there, and then coding for Zikula a decade ago.

So if you can (be gentle, lol) please direct me to how I would go about starting a custom module development with Dreamweaver.

**Comment by lots0logs** [comment]
>What I remember about PHP, and what I know about JS and HTML5 is that they don't need to be compiled. So I am very confused about where I would start out with Dreamweaver.

You're not wrong. Typically they don't need to be compiled but in this case we're not using standard old JavaScript. Since we're using the latest and greatest JavaScript features, it has to be compiled down to the old JavaScript to ensure it works in all browsers. In order to compile it you have to install Node.js and all the JavaScript dependencies. TBH, the easiest way for you to get started would be to follow our documentation to create a Divi dev site with Docker and then use `create-divi-extension` to setup a basic extension that you can then edit to your needs. That way you don't have to figure out all the moving parts just to get started :wink:

**Comment by randomblink** [comment]
ok... I will try that once I get home. I was hoping for something I could configure more quickly. Ah well...

Thank you for your time.
