### ISSUE TITLE
Image not Showing Up on VB

### ISSUE THREAD

**Issue by seph1603** [elegantthemes/create-divi-extension#70]
### Problem Description
Uploaded image not showing up on VB

### Steps To Reproduce
1. Upload an image
2. Image renders when closing visual builder but not when visual builder is active.

file.jsx

```
  render() {

    return (
      <Fragment>
       <div class="myte-my_testimonial">
       		<img src="{ this.props.portrait_url }" alt=" " />
			<div class="myte-my_testimonial_description">
				<div class="myte-my_testimonial_description_inner">
				 {this.props.content()}
				<strong class="myte-my_testimonial_author">{this.props.author}</strong>
				<p class="myte-my_testimonial_meta">{this.props.job}, {this.props.company} . </p>
				</div> 
			</div> 
			</div>
      </Fragment>
    );
  }
```
file.php

```
'portrait_url' => array(
				'label'              => esc_html__( 'Portrait Image URL', 'myte-my-testimonial' ),
				'type'               => 'upload',
				'option_category'    => 'basic_option',
				'upload_button_text' => esc_attr__( 'Upload an image', 'myte-my-testimonial' ),
				'choose_text'        => esc_attr__( 'Choose an Image', 'myte-my-testimonial' ),
				'update_text'        => esc_attr__( 'Set As Image', 'myte-my-testimonial' ),
				'description'        => esc_html__( 'Upload your desired image, or type in the URL to the image you would like to display.', 'myte-my-testimonial' ),
				'toggle_slug'        => 'image',
			)
```

### Screenshot and/or gif
![divi](https://user-images.githubusercontent.com/6620848/40390418-cf76deae-5dda-11e8-9818-fbff2e6fe9b0.gif)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [x] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by seph1603** [comment]
Image src tag had double quotes
