### ISSUE TITLE
componentDidMount is not called when child item is added

### ISSUE THREAD

**Issue by jdurnil** [elegantthemes/create-divi-extension#76]
### Problem Description
I have the following code. I am just playing around trying to understand everything. I have child items being added successfully on the react side, but i have also have a jquery extension that needs to be run on each child item as it is placed in the visual builder. I thought componentDidMount would be the perfect place to do that. I have placed breakpoints in the function and if you create a new page and add the plugin you can add the child items and see them visually but componentDidMount is not called until the page is saved and reloaded. Intermittently you can get it to call in the right place everytime if you add my module after another standard module but it doesn't work everytime

### Steps To Reproduce
1. write a react script to show child items and try to use a jquery extension in componentDidMount to add some functionality.

### Screenshot and/or gif
import React, { Fragment, Component } from 'react';
import jQuery from 'jquery';

// Internal Dependencies
import './style.css';

class HelloWorld extends Component {

	componentDidMount(){
		console.log('hello');
		jQuery(".main").tiltedpage_scroll({
			sectionContainer: "> section",    
			angle: 50,                        
			opacity: true,                    
			scale: true,                      
			outAnimation: true                
		});
	}

	static slug = 'etl_hello_world';
	renderImages(){
		const children = this.props.content;
		console.log(children);
		if(this.props.content) {
			return this.props.content.map((content) => {
				return (
					<section key={content.key}>
						<img src={content.props.attrs.src} alt=''/>
					</section>
				);
			});
		} else{
			return '';
		}
	}
	render() {

		

		return (

				<div className="main">
				{this.renderImages()}
				</div>

		);
	}
}

export default HelloWorld;

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
How about using `componentDidUpdate()` instead? It runs after the `render()` function has finished and I use it for example to setup the lightbox effect on my images:

    componentDidUpdate() {
        const lightbox = findDOMNode(this.refs.lightbox);
        if (!lightbox) return;

        $(lightbox).magnificPopup({
            type: 'image',
            removalDelay: 500,
            mainClass: 'mfp-fade',
            zoom: {
                enabled: true,
                duration: 500,
                opener: function (element) {
                    return element.find('img');
                }
            }
        });
    }

**Comment by jdurnil** [comment]
Thanks! that did it.
