### ISSUE TITLE
DB VB :: new module :: problem with fieldtype composite_structure

### ISSUE THREAD

**Issue by motylo** [elegantthemes/create-divi-extension#79]
### Problem Description
![err](https://user-images.githubusercontent.com/10988614/40561628-2e58be44-605e-11e8-979e-fcbce6642b4f.jpg)

https://www.elegantthemes.com/forum/viewtopic.php?f=190&t=865045&p=4749872#p4749872

There is little bug (tried on Divi Theme, but i suppose that it's builder fault).
Tried to create field type composite_structure in own module.
In standard Divi Builder it shows only tabs, and clicking on them won't show corresponding panel.
When i change to Visual Builder all tabs are clickable and panels are visible.

So bug only shows on Divi Builder.

### Steps To Reproduce
1. Create own module with field type 'composite_structure '
2. Add 2-3 tabs with additional controls
3. Build and test
4. Try to change controls on tab1, tab2, tab3;
5. Change to Visual Builder
6. Try to change controls on tab1 etc.

### Screenshot and/or gif
On screenshot:
1. Top - normal builder - tabs won't work.
2. Bottom - Visual Builder - Panels with controls are visible

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
I'm afraid the Classic Divi Builder doesn't fully support custom settings using the composite type. Also worth noting is that the composite field type is undocumented. We are not ready to guarantee it's API or even its continued existence. Please keep that in mind when considering using it :smiley:
