### ISSUE TITLE
Inline css api feature cannot be used for child items

### ISSUE THREAD

**Issue by jdurnil** [elegantthemes/create-divi-extension#80]
### Problem Description
When using static css(props) to apply inline css to child elements, "content" is not available in props here like it is else where, like accessing this.props.content.props.attrs when rendering child items. So it is impossible to use the static css(props) function for rendering inline css from the visual builder options for child items.

### Steps To Reproduce
1.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by jcdotnet** [comment]
You can use static css(props) as you do in the parent module, you will receive the child props. Anyway I don't like the static approach, I'm going to try to render the styles in a instance of the component so I can use all the props, the state, etc.

**Comment by jdurnil** [comment]
Actually you cannot use static css(props) because "content" is not available there under the props object when you are dealing with child items. Everything coming from the child properties is contained in that "content" key, we are not dealing with two different react classes for parent and child items but the same react class to render both parent and child.

**Comment by jcdotnet** [comment]
I meant that you can use that function in the child component and you will receive the child props (this component props) and not all of them. I opened an issue because we are not receiving the content or the module order. It would be helpful if we can access those values to work in a more reacty way.

**Comment by jdurnil** [comment]
I use this.props.content.attrs. To render my child components

**Comment by lots0logs** [comment]
Sorry for the delayed response! See the parent and child examples [here](https://github.com/elegantthemes/divi-extension-example/tree/master/includes/modules) for the recommended way of doing it.
