### ISSUE TITLE
Where can I find the "List of available fields" and "How to use it" in creating custom divi module?

### ISSUE THREAD

**Issue by tnchuntic** [elegantthemes/create-divi-extension#83]
### Problem Description
This is not a bug or issue. Just a feedback and what to be pointed in the right direction.

1. I can't find a list of available fields that can be used in the custom module creation. ex. select option for the number of columns, a layout of display and etc.

2. I can't find a documentation on how to use each field. ex. "categories"
`'include_categories' => array(
                'label' => esc_html__('Include Categories', 'et_builder'),
                'type' => 'categories',
                'option_category' => 'basic_option',
                'description' => esc_html__('Select the categories that you would like to include in the feed.', 'et_builder'),
                'toggle_slug' => 'main_content',
                'computed_affects' => array(
                    '__projects',
                ),
                'taxonomy_name' => 'project_category',
            ),`
3. How to populate select options dynamically for a specific field. ex. Post Type field -> array('page', 'post', 'projects') etc.

Hope you can point me in the right direction thanks.

### Steps To Reproduce
n/a

### Screenshot and/or gif
n/a

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by lots0logs** [comment]
Sorry for the delayed response! You can find documentation for the field types [here](https://www.elegantthemes.com/documentation/developers/divi-module/defining-module-settings/). To populate select options dynamically you must do that from within your module's `get_fields()` method before returning the array of fields. I hope that helps :smiley:

**Comment by mortan66** [comment]
This list doesn't seem complete. I see other modules using types like "upload", "upload-gallery" or "computed", which are not documented in the provided link. Is there a complete list anywhere or a non-minified code file where I can see all available types?

**Comment by Dnatalyaalex** [comment]
> Sorry for the delayed response! You can find documentation for the field types [here](https://www.elegantthemes.com/documentation/developers/divi-module/defining-module-settings/). To populate select options dynamically you must do that from within your module's `get_fields()` method before returning the array of fields. I hope that helps 😃

Hi. Can you please tell where I can find a description such fields types like tiny_mce and which else exist (full list)?
Thanks.

**Comment by holmesadrianh** [comment]
I would also like to know. I notice a field type 'upload' but do not see any documentation on it?

**Comment by Jgruet** [comment]
> This list doesn't seem complete. I see other modules using types like "upload", "upload-gallery" or "computed", which are not documented in the provided link. Is there a complete list anywhere or a non-minified code file where I can see all available types?

Always not a complete documentation ?
