### ISSUE TITLE
VB :: React component :: accessing the parent props

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#85]
please delete, this issue was React related, nothing to do with the new Divi API.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by jcdotnet** [comment]
Hi again, I've changed the render method to add the props I want to pass to the child modules:

Parent_Module:
```
render() {
  return (  
      <Fragment>
          {this.props.content.map(elem => React.isValidElement(elem) ? React.cloneElement(elem, { property: this.props.property_type }) : elem )}
      </Fragment>
  );
}
```
Child_Module (cloned element with the new prop):

`this.props.property` is still inaccessible, why???  It was added in the `React.cloneElement `method...

Accessing the parent props is very important when creating Divi modules with items, hope someone can help, thank you.

**Comment by MarieComet** [comment]
Hi @jcdotnet can you share how do you achieve this : 
"To achieve that we only have to pass the props from the parent to each child by itering over this.props.content." ?
Thanks

**Comment by jcdotnet** [comment]
```
this.props.content.forEach(elem => { 
   // check elem (is not null, is a React element, ...)
   elem.props.attrs.parent_prop  = this.props.parent_prop; // adds parent_prop to the item
   console.log(elem.props.attrs); // item props 
}
```
Hope it helps

**Comment by MarieComet** [comment]
thanks you!

**Comment by MarieComet** [comment]
Hi,
after some tests : yes it's work, but it's not triggering child update when parent props are updated.
I mean, if in my child module we have a condition on this props value, this condition isn't effective.
