### ISSUE TITLE
Having to add all child item css from advanced fields manually in render method

### ISSUE THREAD

**Issue by jdurnil** [elegantthemes/create-divi-extension#88]
### Problem Description
When I have child items in the module i am having to add all css from the advanced fields for the child manually in the render method. i am actually having to recreate the logic that the advanced field are using on regular items. Is this normal.

### Steps To Reproduce
1. Create any child items on a module and try to  use their advanced field settings, these are only available in this.props.content.attrs, you have to recreate all the code to use advanced field from module like border, box shadow etcetera in the render method which i know is a performance hit.

### Screenshot and/or gif
`const border_radius_string = attr.border_radii;
				const border_radius_array = border_radius_string !== undefined ? border_radius_string.split('|'):'';

				const borderTopLeftRadius = border_radius_array ? border_radius_array[1]: '0px';
				const borderTopRightRadius = border_radius_array ? border_radius_array[2]: '0px';
				const borderBottomRightRadius = border_radius_array ? border_radius_array[3]: '0px';
				const borderBottomLeftRadius = border_radius_array ? border_radius_array[4]: '0px';
				const divStyle = {
					height: content.props.attrs.height,

				};
				const imgStyle = {
					borderTopLeftRadius,
					borderTopRightRadius,
					borderBottomRightRadius,
					borderBottomLeftRadius,
					borderRadius: attr.border_radii,
					boxShadow: `${attr.box_shadow_horizontal} ${attr.box_shadow_vertical} ${attr.box_shadow_blur} ${attr.box_shadow_spread} ${attr.box_shadow_color}`,
					borderStyle: border_style,
					borderColor: attr.border_color_all !== undefined ? attr.border_color_all : '#00000',
					borderLeftStyle: attr.border_style_left !== undefined ? attr.border_style_left: attr.border_style_all,
					borderLeftColor: attr.border_color_left !== undefined ? attr.border_color_left: attr.border_color_all,
					borderTopStyle: attr.border_style_top !== undefined ? attr.border_style_top: attr.border_style_all,
					borderTopColor: attr.border_color_top !== undefined ? attr.border_color_top: attr.border_color_all,
					borderRightStyle: attr.border_style_right !== undefined ? attr.border_style_right: attr.border_style_all,
					borderRightColor: attr.border_color_right !== undefined ? attr.border_color_right: attr.border_color_all,
					borderBottomStyle: attr.border_style_bottom !== undefined ? attr.border_style_bottom: attr.border_style_all,
					borderBottomColor: attr.border_color_bottom !== undefined ? attr.border_color_bottom: attr.border_color_all,
					borderWidth: border_width
				}
				return (
					<section className="hello_item" style={divStyle} key={content.key}>
						<img src={content.props.attrs.src} style={imgStyle} alt=''/>
					</section>
				);
			});`

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by xxtesaxx** [comment]
I think you might be doing something wrong and therefore having these issues. I just gave it a try and border styles are perfectly applied to my child module:

![image](https://user-images.githubusercontent.com/3000808/41061818-2fab80cc-69d4-11e8-84be-6d3c9d24d7fd.png)

You should post your field config so the devs can identify what might be going wrong.

**Comment by xxtesaxx** [comment]
Actually I might know what you are doing wrong. Are you using a React component per child in which you return a html? Are you using this.props.content in the parent to output the html genreated by each child? Does your html contain the necessary order classes and data-adresses?

![image](https://user-images.githubusercontent.com/3000808/41062030-caeb42a2-69d4-11e8-9ae9-02abc4361575.png)

**Comment by jdurnil** [comment]
I am not using a react component per child should I be? i am using this.props.content to to render the html generated by each child, the html does not contain the necessary order classes and data-adresses, how do i get those, what am i doing wrong?

**Comment by jdurnil** [comment]
When i try using this.props.content in my parent I get the error below, it is trying to render the content "object", is there something i am doing wrong. I am following the example exactly.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `t`.
    in t (created by t)
    in div (at HelloWorld.jsx:17)
    in div (at HelloWorld.jsx:15)
    in CustomCtaParent (created by t)
    in div (created by t)
    in div (created by ETBuilderModule)
    in t (created by ETBuilderModule)
    in ETBuilderModule (created by t)
    in t (created by t)
    in t (created by ETBuilderColumn)
    in div (created by ETBuilderColumn)
    in t (created by ETBuilderColumn)
    in ETBuilderColumn (created by ETBuilderRow)
    in div (created by ETBuilderRow)
    in t (created by ETBuilderRow)
    in ETBuilderRow (created by ETBuilderSection)
    in div (created by ETBuilderSection)
    in t (created by ETBuilderSection)
    in ETBuilderSection (created by ETBuilderRoot)
    in div (created by t)
    in t (created by ETBuilderRoot)
    in div (created by ETBuilderRoot)
    in ETBuilderRoot
    in t

**Comment by lots0logs** [comment]
Actually you must use a react component to render your child modules as is shown in our example:

https://github.com/elegantthemes/divi-extension-example/blob/master/includes/modules/CustomCtaParent/CustomCtaParent.jsx

https://github.com/elegantthemes/divi-extension-example/blob/master/includes/modules/CustomCtaChild/CustomCtaChild.jsx

**Comment by jdurnil** [comment]
I got it now, i wasn't importing the child component in index.js, thanks for the help
