### ISSUE TITLE
After adding new fields in get_fields() changing not showing in module. 

### ISSUE THREAD

**Issue by sharazghouri** [elegantthemes/create-divi-extension#92]
### Problem Description

Screen shot when i add image field
![image](https://user-images.githubusercontent.com/17900945/40916768-6de47c9c-681a-11e8-8a38-d7f8568b5edc.png)

After adding two new fields 
![image](https://user-images.githubusercontent.com/17900945/40916807-865d2a6c-681a-11e8-8315-f297a01ac74b.png)

Result same as before
![image](https://user-images.githubusercontent.com/17900945/40916826-a3fd2aae-681a-11e8-845f-5acb818e5e4d.png)

Note:  run many times start and build command but same result. 
### Steps To Reproduce
1.

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [x] Detailed description
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by VladET** [comment]
@sharazghouri Do they show up in the Visual Builder? If they do, clear your local storage and they should display in the Classic Builder as well.

**Comment by antonkor** [comment]
I too am getting this issue. Just updated to the latest Divi theme just to make sure.

I see the new fields in the Visual Builder, but not classic builder. 

I've cleared the local storage via js console 

window.localStorage.clear()

as well as using the Clear Cache plugin (using the Clear local storage option): 
https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn


any other suggestions?

**Comment by VladET** [comment]
@antonkor That is strange. After you clear the local storage and enter, ```localStorage``` is it empty?

![image](https://user-images.githubusercontent.com/1061516/40966456-34b46b36-68b9-11e8-91b6-f9d0860d7006.png)

You can also try in a private/incognito window.

**Comment by antonkor** [comment]
heres a recording of whats going on: 
https://cl.ly/2Q3r3K141L15

with incognito i get a loading icon in the center for 1 minute then the same thing happens, no new fields shown in classic builder:
https://cl.ly/1T3e263L0Y2o

here is the php file:
https://pastebin.com/RnQaicyG

here is the jsx file:
https://pastebin.com/Xu6JvneS

Although i keep getting an error on the Frontend Builder, when i save the changes they are all saved, not sure if it's related, that error is the next thing i need to tackle:
https://cl.ly/1g321n0f2h0R

**Comment by motylo** [comment]
Steps:
1. Remove module from post (every SIR_Proj_Description module in post);
2. Clear localstorage;
3. Clear localstorage;
4. Reload page;
5. Clear localstorage ;)
6. Try to add module after 5sec;
7. Loader should spin a little longer.

I found that clearing localstorage is not enough if you have module implemented on page.

**Comment by antonkor** [comment]
thanks @motylo for the suggestion, i've been doing all kinds of clearing and hoping around.
https://cl.ly/2T322l2Z1E1G

is it normal to see such values in the local storage?
https://cl.ly/1p2Z201k2D0H

**Comment by antonkor** [comment]
I dont even know what just happened, but while i was developing a new module, clearing local storage plus refreshing the page made it so the classic builder now shows the all the fields i created on all modules. 

/shrug

**Comment by sharazghouri** [comment]
So developer need to clear local storage after every change .

**Comment by VladET** [comment]
@sharazghouri Yes, after every change to the module options since the Classic Builder module templates are stored in the browser local storage. 

Is everything working for you after clearing the local storage?

**Comment by antonkor** [comment]
@sharazghouri you have to clear the localstorage while a divi module is open, then while the module is still open you have to refresh the page. if you close the divi module before refreshing the page, all the old module data is re-saved back into localstorage and refreshing the page will only show you the old data. 

well thats the behavior i've found.

**Comment by lots0logs** [comment]
That is how it works. Though typically the workflow would be to close the module settings first, clear local storage, and then refresh the page. To be clear, this applies to the Classic Divi Builder only.
